force-app/main/default/objects/Geo_Targeting__c/Geo_Targeting__c.object-meta.xml
<CustomObject>
    <label>Geo Targeting (old)</label>
    <nameField>
        <label>Geo Targeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geo Targetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Geo_Targeting__c/fields/Campaign_City__c.field-meta.xml
<CustomField>
    <fullName>Campaign_City__c</fullName>
    <label>Campaign City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Geo_Targeting__c/fields/Campaign_Country__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Country__c</fullName>
    <label>Campaign Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Targeting_Campaign_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Geo_Targeting__c/fields/Campaign_DMA__c.field-meta.xml
<CustomField>
    <fullName>Campaign_DMA__c</fullName>
    <label>Campaign DMA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Targeting_Campaign_DMA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Geo_Targeting__c/fields/Campaign_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Campaign_State_Province__c</fullName>
    <label>Campaign State/Province</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Campaign_Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Targeting_Campaign_State_Province</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Geo_Targeting__c/fields/Campaign_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Zip_Code__c</fullName>
    <label>Campaign Zip Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Geo_Targeting__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Geo_Targeting</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Insertion_Order__c.field-meta.xml
<CustomField>
    <fullName>Insertion_Order__c</fullName>
    <description>This field displays the insertion order number</description>
    <label>Insertion Order Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Original_Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Opportunity_Id__c</fullName>
    <description>Used to identify the original opportunity from which an opportunity is cloned. This will be blank on opportunities created from scratch and not cloned</description>
    <label>Original Opportunity Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Targeting__c.field-meta.xml
<CustomField>
    <fullName>Targeting__c</fullName>
    <label>Targeting</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Advertising.recordType-meta.xml
<RecordType>
    <fullName>Advertising</fullName>
    <active>true</active>
    <businessProcess>Advertising</businessProcess>
    <label>Advertising</label>
</RecordType>

force-app/main/default/objects/Targeting__c/Targeting__c.object-meta.xml
<CustomObject>
    <label>Targeting</label>
    <nameField>
        <label>Targeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targeting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Targeting__c/fields/Behavioral__c.field-meta.xml
<CustomField>
    <fullName>Behavioral__c</fullName>
    <label>Behavioral</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BehavorialCheck__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>First Party</fullName>
            </value>
            <value>
                <fullName>Third Party</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Targeting__c/fields/Campaign_City__c.field-meta.xml
<CustomField>
    <fullName>Campaign_City__c</fullName>
    <label>Campaign City</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Targeting__c/fields/Campaign_Country__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Country__c</fullName>
    <defaultValue>IF(ISPICKVAL($User.User_Region__c, &quot;Japan&quot;),&quot;JP - Japan&quot;,IF(ISPICKVAL($User.User_Region__c, &quot;EMEA&quot;),&quot;GB - United Kingdom of Great Britain and Northern Ireland&quot;,&quot;US - United States of America&quot;))</defaultValue>
    <label>Campaign Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Targeting_Campaign_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Targeting__c/fields/Campaign_State_Province__c.field-meta.xml
<CustomField>
    <fullName>Campaign_State_Province__c</fullName>
    <label>Campaign State/Province</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Targeting_Campaign_State_Province</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Targeting__c/fields/Campaign_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Zip_Code__c</fullName>
    <label>Campaign Zip Code</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Targeting__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Used for rollup and workflow</description>
    <label>Count</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Targeting__c/fields/Custom_Description__c.field-meta.xml
<CustomField>
    <fullName>Custom_Description__c</fullName>
    <label>Custom Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Targeting__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event Apex</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Targeting__c/fields/Insertion_Order__c.field-meta.xml
<CustomField>
    <fullName>Insertion_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insertion Order</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Targeting</relationshipLabel>
    <relationshipName>Targeting</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Targeting__c/fields/Keywords__c.field-meta.xml
<CustomField>
    <fullName>Keywords__c</fullName>
    <label>Keywords</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Targeting__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Targeting Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Audience</fullName>
            </value>
            <value>
                <fullName>Keyword</fullName>
            </value>
            <value>
                <fullName>Vertical</fullName>
            </value>
            <value>
                <fullName>Behavioral</fullName>
            </value>
            <value>
                <fullName>Trend</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Targeting__c/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <label>VerticalOld</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
                <label>Business &amp; Finance</label>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Fashion</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
                <label>Food &amp; Drink</label>
            </value>
            <value>
                <fullName>Gaming</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
                <label>Health &amp; Wellness</label>
            </value>
            <value>
                <fullName>Home</fullName>
                <label>Home &amp; Garden</label>
            </value>
            <value>
                <fullName>Humor</fullName>
            </value>
            <value>
                <fullName>Lifetstyle</fullName>
                <label>Lifetstyles</label>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>News</fullName>
            </value>
            <value>
                <fullName>Ron</fullName>
                <label>RON</label>
            </value>
            <value>
                <fullName>Social Networks</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Targeting__c/recordTypes/Targeting.recordType-meta.xml
<RecordType>
    <fullName>Targeting</fullName>
    <active>true</active>
    <label>Targeting</label>
</RecordType>

force-app/main/default/globalValueSets/Targeting_Campaign_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD - Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>AE - United Arab Emirates</fullName>
    </customValue>
    <customValue>
        <fullName>AF - Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>AG - Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>AI - Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>AL - Albania</fullName>
    </customValue>
    <customValue>
        <fullName>AM - Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>AO - Angola</fullName>
    </customValue>
    <customValue>
        <fullName>AQ - Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>AR - Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>AS - American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>AT - Austria</fullName>
    </customValue>
    <customValue>
        <fullName>AU - Australia</fullName>
    </customValue>
    <customValue>
        <fullName>AW - Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>AX - Åland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>AZ - Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>BA - Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>BB - Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>BD - Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>BE - Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>BF - Burkina Faso</fullName>
    </customValue>
    <customValue>
        <fullName>BG - Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>BH - Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>BI - Burundi</fullName>
    </customValue>
    <customValue>
        <fullName>BJ - Benin</fullName>
    </customValue>
    <customValue>
        <fullName>BL - Saint Barthélemy</fullName>
    </customValue>
    <customValue>
        <fullName>BM - Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>BN - Brunei Darussalam</fullName>
    </customValue>
    <customValue>
        <fullName>BO - Bolivia (Plurinational State of)</fullName>
    </customValue>
    <customValue>
        <fullName>BQ - Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <masterLabel>Targeting Campaign Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Targeting_Campaign_DMA.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>662 - Abilene-Sweetwater TX</fullName>
    </customValue>
    <customValue>
        <fullName>525 - Albany GA</fullName>
    </customValue>
    <customValue>
        <fullName>532 - Albany-Schenectady-Troy NY</fullName>
    </customValue>
    <customValue>
        <fullName>790 - Albuquerque-Santa Fe NM</fullName>
    </customValue>
    <customValue>
        <fullName>644 - Alexandria LA</fullName>
    </customValue>
    <customValue>
        <fullName>583 - Alpena MI</fullName>
    </customValue>
    <customValue>
        <fullName>634 - Amarillo TX</fullName>
    </customValue>
    <customValue>
        <fullName>743 - Anchorage AK</fullName>
    </customValue>
    <customValue>
        <fullName>524 - Atlanta GA</fullName>
    </customValue>
    <customValue>
        <fullName>520 - Augusta GA</fullName>
    </customValue>
    <customValue>
        <fullName>635 - Austin TX</fullName>
    </customValue>
    <customValue>
        <fullName>800 - Bakersfield CA</fullName>
    </customValue>
    <customValue>
        <fullName>512 - Baltimore MD</fullName>
    </customValue>
    <customValue>
        <fullName>537 - Bangor ME</fullName>
    </customValue>
    <customValue>
        <fullName>716 - Baton Rouge LA</fullName>
    </customValue>
    <customValue>
        <fullName>692 - Beaumont-Port Arthur TX</fullName>
    </customValue>
    <customValue>
        <fullName>821 - Bend OR</fullName>
    </customValue>
    <customValue>
        <fullName>756 - Billings MT</fullName>
    </customValue>
    <customValue>
        <fullName>746 - Biloxi-Gulfport MS</fullName>
    </customValue>
    <customValue>
        <fullName>502 - Binghamton NY</fullName>
    </customValue>
    <customValue>
        <fullName>630 - Birmingham AL</fullName>
    </customValue>
    <customValue>
        <fullName>559 - Bluefield-Beckley-Oak Hill WV</fullName>
    </customValue>
    <customValue>
        <fullName>757 - Boise ID</fullName>
    </customValue>
    <customValue>
        <fullName>506 - Boston MA-Manchester NH</fullName>
    </customValue>
    <customValue>
        <fullName>736 - Bowling Green KY</fullName>
    </customValue>
    <customValue>
        <fullName>514 - Buffalo NY</fullName>
    </customValue>
    <customValue>
        <fullName>523 - Burlington VT-Plattsburgh NY</fullName>
    </customValue>
    <customValue>
        <fullName>754 - Butte-Bozeman MT</fullName>
    </customValue>
    <customValue>
        <fullName>767 - Casper-Riverton WY</fullName>
    </customValue>
    <customValue>
        <fullName>637 - Cedar Rapids-Waterloo-Iowa City &amp; Dubuque IA</fullName>
    </customValue>
    <masterLabel>Targeting Campaign DMA</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Targeting_Campaign_State_Province.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AK - Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>AL - Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alberta - AB - Alberta</fullName>
    </customValue>
    <customValue>
        <fullName>AR - Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>AZ - Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>British Columbia - BC - British Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>CA - California</fullName>
    </customValue>
    <customValue>
        <fullName>CO - Colorado</fullName>
    </customValue>
    <customValue>
        <fullName>CT - Connecticut</fullName>
    </customValue>
    <customValue>
        <fullName>DC - District Of Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>DE - Delaware</fullName>
    </customValue>
    <customValue>
        <fullName>FL - Florida</fullName>
    </customValue>
    <customValue>
        <fullName>GA - Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>HI - Hawaii</fullName>
    </customValue>
    <customValue>
        <fullName>IA - Iowa</fullName>
    </customValue>
    <customValue>
        <fullName>ID - Idaho</fullName>
    </customValue>
    <customValue>
        <fullName>IL - Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>IN - Indiana</fullName>
    </customValue>
    <customValue>
        <fullName>KS - Kansas</fullName>
    </customValue>
    <customValue>
        <fullName>KY - Kentucky</fullName>
    </customValue>
    <customValue>
        <fullName>LA - Louisiana</fullName>
    </customValue>
    <customValue>
        <fullName>MA - Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>Manitoba - MB - Manitoba</fullName>
    </customValue>
    <customValue>
        <fullName>MD - Maryland</fullName>
    </customValue>
    <customValue>
        <fullName>ME - Maine</fullName>
    </customValue>
    <customValue>
        <fullName>MI - Michigan</fullName>
    </customValue>
    <customValue>
        <fullName>MN - Minnesota</fullName>
    </customValue>
    <customValue>
        <fullName>MO - Missouri</fullName>
    </customValue>
    <customValue>
        <fullName>MS - Mississippi</fullName>
    </customValue>
    <customValue>
        <fullName>MT - Montana</fullName>
    </customValue>
    <masterLabel>Targeting Campaign State/Province</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityTriggerHandler.cls
/**
Class Name - OpportunityTriggerHandler
Description - Class called from trigger 'OpportunityTrigger' to fetch the Targeting and GeoTargeting records of Opportunity on cloning

Method Name - cloneRelatedRecords
Description - Future methods fetch all the Targeting and Geotargeting records from parent Opportunity and insert with child Opportunity 
              if Origional Opportunity Id is not equal to null
**/

public with sharing class OpportunityTriggerHandler{

@future
public static void cloneRelatedRecords(Set<Id> setOfOppID){

List<Targeting__c> listOfTargeting = new List<Targeting__c>();
List<Targeting__c> newListofTargeting;
List<Geo_Targeting__c> listOfGeoTargeting = new List<Geo_Targeting__c>();
List<Geo_Targeting__c> newListOfGeoTargeting;
Map<String,String> mapOforiOppIdWithOppId = new Map<String,String>();
Set<String> oriOppId = new Set<String>();
List<Opportunity> updatedOppId = new List<Opportunity>();

List<Opportunity> listOfOpp = [Select ID,Original_Opportunity_Id__c from Opportunity where Id in: setOfOppID];

for(Opportunity o : listOfOpp )
{
    mapOforiOppIdWithOppId.put(o.Original_Opportunity_Id__c,o.id );
    
    oriOppId.add(o.Original_Opportunity_Id__c);
}

if(!oriOppId.isempty() && !oriOppId.contains(null))
{
    
    listOfTargeting =[Select Name,Behavioral__c,Count__c,Custom_Description__c,Description__c,Event__c,Keywords__c,Type__c,Vertical__c,Insertion_Order__c from Targeting__c where Insertion_Order__c in: oriOppId];
    listOfGeoTargeting =[select Name,Campaign_City__c,Campaign_Country__c,Campaign_DMA__c,Campaign_State_Province__c,Campaign_Zip_Code__c,Opportunity__c from Geo_Targeting__c where Opportunity__c in: oriOppId];
    
}

if(!listOfTargeting.isempty() && listOfTargeting != null)
{
    Map<String,List<Targeting__c>> mapOfOidWithTid = new Map<String,List<Targeting__c>>();
    newListofTargeting = new List<Targeting__c>();
    for(Targeting__c target : ListOfTargeting )
    {
        if(mapOfOidWithTid.containskey(target.Insertion_Order__c))
        {
            mapOfOidWithTid.get(target.Insertion_Order__c).add(target);
        }
        else
        {
            mapOfOidWithTid.put(target.Insertion_Order__c,new List<Targeting__c>{target});
        }
    }
    
    for(String s : mapOfOidWithTid.keySet())
    {
        for(Targeting__c t : mapOfOidWithTid.get(s))
        {
            Targeting__c targetNew = t.clone();
            targetnew.Insertion_Order__c = mapOforiOppIdWithOppId.get(s.substring(0, 15));            
            newListofTargeting.add(targetNew);
        }
    }
    
    try
    {
        insert newListofTargeting;
    }
    catch(Exception e)
    {
        for(Opportunity opp : listOfOpp)
        {
            opp.addError('The following error occured' + e);
        }
        
    }

}

if(!listOfGeoTargeting.isempty() && listOfGeoTargeting != null)
{
    Map<String,List<Geo_Targeting__c >> mapOfOidWithGtid = new Map<String,List<Geo_Targeting__c >>();
    newListOfGeoTargeting = new List<Geo_Targeting__c >();
    for(Geo_Targeting__c gTarget : listOfGeoTargeting)
    {
        if(mapOfOidWithGtid.containskey(gtarget.Opportunity__c ))
        {
            mapOfOidWithGtid.get(gTarget.Opportunity__c ).add(gTarget);
        }
        else
        {
            mapOfOidWithGtid.put(gTarget.Opportunity__c ,new List<Geo_Targeting__c >{gTarget});
        }
    }
    
    for(String s : mapOfOidWithGtid.keySet())
    {
        for(Geo_Targeting__c gt : mapOfOidWithGtid.get(s))
        {
            Geo_Targeting__c gTargetNew = gt.clone();
            gTargetnew.Opportunity__c = mapOforiOppIdWithOppId.get(s.substring(0, 15));
            newListOfGeoTargeting .add(gTargetNew);
        }
    }
    
    try
    {
        insert newListOfGeoTargeting ;
    }
    catch(Exception e)
    {
        for(Opportunity opp : listOfOpp)
        {
            opp.addError('The following error occured' + e);
        }
        
    }

}


for(Opportunity opp : listOfOpp )
{
    opp.Original_Opportunity_Id__c = string.valueof(opp.Id).substring(0, 15);
    updatedOppId.add(opp);

}
try
{
    Update updatedOppId ;
}
catch(Exception e)
{
    for(Opportunity opp : listOfOpp)
    {
        opp.addError('The following error occured' + e);
    }
    
}
}

//this method sets the Pricebook on Opportunity at the time of insert
// Commenting the below code as we are handling the below logic from flow.
/*public static void setPricebookOnOppty(List<Opportunity> newOpptyList){
   //Sports Record type Id
   Id sportsRecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sports').getRecordTypeId();
   //Advertising record type Id
   Id adRecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Advertising').getRecordTypeId();
   
   Id sportsPBId, adPBId, stdPBId;
   
   List<Pricebook2> pbList = new List<Pricebook2>([Select Id, Name From Pricebook2]);
   
   if(pbList.size() > 0){
      for(Pricebook2 pb :pbList){
         if(pb.Name == 'Sports Opportunity'){
            sportsPBId = pb.Id;
         } else if(pb.Name == 'Advertising Opportunity'){
            adPBId = pb.Id;
         } else if(pb.Name == 'Standard Price Book'){
            stdPBId = pb.Id;
         }
      }
   }
   
   //setting Pricebook on Opportunity
   for(Opportunity o :newOpptyList){
      if(o.RecordTypeId == sportsRecTypeId){
         o.Pricebook2Id = sportsPBId;
      } else if(o.RecordTypeId == adRecTypeId){
         o.Pricebook2Id = adPBId;
      } else{
         o.Pricebook2Id = stdPBId;
      } 
   }
} */

}