force-app/main/default/objects/Item_Snapshot__c/Item_Snapshot__c.object-meta.xml
<CustomObject>
    <label>Item Snapshot</label>
    <nameField>
        <label>Item Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_Snapshot__c/fields/Item_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Full_Name__c</fullName>
    <label>Item Full Name</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Item_Snapshot_Field__c/Item_Snapshot_Field__c.object-meta.xml
<CustomObject>
    <label>Item Snapshot Field</label>
    <nameField>
        <label>Item Snapshot Fields Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Snapshot Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_Snapshot_Field__c/fields/Decimal_Places__c.field-meta.xml
<CustomField>
    <fullName>Decimal_Places__c</fullName>
    <description>getScale</description>
    <inlineHelpText>getScale</inlineHelpText>
    <label>Decimal Places</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item_Snapshot_Field__c/fields/Default_Value__c.field-meta.xml
<CustomField>
    <fullName>Default_Value__c</fullName>
    <description>getDefaultValue if not null or
getDefaultValueFormula if not null</description>
    <inlineHelpText>getDefaultValue if not null or
getDefaultValueFormula if not null</inlineHelpText>
    <label>Default Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Item_Snapshot_Field__c/fields/Field_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Api_Name__c</fullName>
    <description>getLocalName</description>
    <inlineHelpText>getLocalName</inlineHelpText>
    <label>Field Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_Snapshot_Field__c/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <description>getLabel</description>
    <inlineHelpText>getLabel</inlineHelpText>
    <label>Field Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_Snapshot_Field__c/fields/Filtered__c.field-meta.xml
<CustomField>
    <fullName>Filtered__c</fullName>
    <description>getFilteredLookupInfo.isOptionalFilter</description>
    <inlineHelpText>getFilteredLookupInfo.isOptionalFilter</inlineHelpText>
    <label>Filtered</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Filter</fullName>
            </value>
            <value>
                <fullName>Filter Optional</fullName>
            </value>
            <value>
                <fullName>Filter Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item_Snapshot_Field__c/fields/Formula__c.field-meta.xml
<CustomField>
    <fullName>Formula__c</fullName>
    <description>getCalculatedFormula</description>
    <inlineHelpText>getCalculatedFormula</inlineHelpText>
    <label>Formula</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Item_Snapshot_Field__c/fields/Item_Snapshot__c.field-meta.xml
<CustomField>
    <fullName>Item_Snapshot__c</fullName>
    <label>Item Snapshot</label>
    <referenceTo>Item_Snapshot__c</referenceTo>
    <relationshipLabel>Item Snapshot Fields</relationshipLabel>
    <relationshipName>Item_Snapshot_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item_Snapshot_Field__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <description>getLength if text or
getPrecision if number</description>
    <inlineHelpText>getLength if text or
getPrecision if number</inlineHelpText>
    <label>Length</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item_Snapshot_Field__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>getType</description>
    <inlineHelpText>getType</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CollectFieldsBatch.cls
public class CollectFieldsBatch implements Database.Batchable<Item_Snapshot__c> {
	
	id currentSnapShotId {get; set;}
	string sessionId {get; set;}
	Item_Snapshot__c[] objectSnapshotList {get;set;}
	
	public CollectFieldsBatch(id snapShotId, string sesnId, Item_Snapshot__c[] snapshotList) {
		currentSnapShotId = snapShotId;
		sessionId = sesnId;
		objectSnapshotList = snapshotList;
	}
	
	public Iterable<Item_Snapshot__c> start(Database.BatchableContext BC) {
		return objectSnapshotList;
	}

   	public void execute(Database.BatchableContext BC, List<Item_Snapshot__c> scope) {
		Map<String, Schema.SObjectType> SobjectSchemaMap = Schema.getGlobalDescribe();
		list<Item_Snapshot_Field__c> allItemSnapshotFields = new list<Item_Snapshot_Field__c>();
		for (Item_Snapshot__c itsn : scope) {
			Schema.DescribeSObjectResult SobjectResult = SobjectSchemaMap.get(itsn.Item_Full_Name__c).getDescribe();
			Map<String, Schema.SObjectField> SobjtFieldMap = SobjectResult.fields.getMap();
			for (Schema.SObjectField SobjtField : SobjtFieldMap.values()) {
				allItemSnapshotFields.add(ConvertFieldToItemSnapshotField(SobjtField, itsn.Id));
			}
		}
		Try{
			insert allItemSnapshotFields;
		}
		Catch(exception e){
			system.debug(logginglevel.info, '*****'+e);
		}
	}

	Item_Snapshot_Field__c ConvertFieldToItemSnapshotField(Schema.SObjectField SobjtField, Id i) {
		Item_Snapshot_Field__c isf = new Item_Snapshot_Field__c();
			isf.name = SobjtField.getDescribe().getLabel().left(80);
			isf.Field_Api_Name__c = SobjtField.getDescribe().getLocalName();
			isf.Field_Label__c = SobjtField.getDescribe().getLabel();
			isf.Item_Snapshot__c = i;
			isf.Type__c = String.valueof(SobjtField.getDescribe().getType());
			if (SobjtField.getDescribe().getScale() > 0) {
				isf.Decimal_Places__c = SobjtField.getDescribe().getScale();
			}
			if (SobjtField.getDescribe().getDefaultValue() != null) {
				isf.Default_Value__c = String.valueof(SobjtField.getDescribe().getDefaultValue());
			} else if (SobjtField.getDescribe().getDefaultValueFormula() != null) {
				isf.Default_Value__c = SobjtField.getDescribe().getDefaultValueFormula();
			}
			if (SobjtField.getDescribe().getFilteredLookupInfo() != null) {
				if (SobjtField.getDescribe().getFilteredLookupInfo().isOptionalFilter() == true) {
					isf.Filtered__c = 'Filter Optional';
				} else {
					isf.Filtered__c = 'Filter Required';
				}
			} else {
				isf.Filtered__c = 'No Filter';
			}
			isf.Formula__c = SobjtField.getDescribe().getCalculatedFormula();
			if (SobjtField.getDescribe().getSoapType() == Schema.SoapType.String) {
				isf.Length__c = SobjtField.getDescribe().getLength();
			} else if (SobjtField.getDescribe().getSoapType() == Schema.SoapType.Double || SobjtField.getDescribe().getSoapType() == Schema.SoapType.Integer) {
				isf.Length__c = SobjtField.getDescribe().getPrecision();
			}
		return isf;
	}
	
	public void finish(Database.BatchableContext BC) {}
	
}