force-app/main/default/objects/Item_Snapshot__c/Item_Snapshot__c.object-meta.xml
<CustomObject>
    <label>Item Snapshot</label>
    <nameField>
        <label>Item Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_Snapshot__c/fields/Created_By__c.field-meta.xml
<CustomField>
    <fullName>Created_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Created By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Item_Snapshots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item_Snapshot__c/fields/Evaluation_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Criteria__c</fullName>
    <label>Evaluation Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_Snapshot__c/fields/Filter_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Filter_Criteria__c</fullName>
    <label>Filter Criteria</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Item_Snapshot__c/fields/Filter_Logic__c.field-meta.xml
<CustomField>
    <fullName>Filter_Logic__c</fullName>
    <label>Filter Logic</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Item_Snapshot__c/fields/Filter_or_Formula__c.field-meta.xml
<CustomField>
    <fullName>Filter_or_Formula__c</fullName>
    <label>Filter or Formula</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Filter</fullName>
            </value>
            <value>
                <fullName>Formula</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item_Snapshot__c/fields/Item_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Full_Name__c</fullName>
    <label>Item Full Name</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Item_Snapshot__c/fields/Last_Modified_By__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Modified By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Item_Snapshots1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item_Snapshot__c/fields/Rule_Criteria_Formula__c.field-meta.xml
<CustomField>
    <fullName>Rule_Criteria_Formula__c</fullName>
    <label>Rule Criteria Formula</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Item_Snapshot__c/fields/System_Snapshot__c.field-meta.xml
<CustomField>
    <fullName>System_Snapshot__c</fullName>
    <label>System Snapshot</label>
    <referenceTo>System_Snapshot__c</referenceTo>
    <relationshipLabel>Item Snapshots</relationshipLabel>
    <relationshipName>Item_Snapshots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item_Snapshot__c/fields/Workflow_Action_Name_Type__c.field-meta.xml
<CustomField>
    <fullName>Workflow_Action_Name_Type__c</fullName>
    <label>Workflow Action Name - Type</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/System_Snapshot__c/System_Snapshot__c.object-meta.xml
<CustomObject>
    <label>System Snapshot</label>
    <nameField>
        <displayFormat>SysSnap - {000000}</displayFormat>
        <label>System Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CollectWorkflowRuleBatch.cls
public class CollectWorkflowRuleBatch implements Database.Batchable<string>, Database.Stateful, Database.AllowsCallouts {

	list<String> fullnameList {get; set;}
	String ssnId {get;set;}
	map<String, MetadataService.FileProperties> filePropertiesMap {get; set;}
	list<MetadataService.IReadResult> readResult = new list<MetadataService.IReadResult>();
	id snapShotId {get; set;}
	MetadataService.MetadataPort service {get; set;}
	list<Item_Snapshot__c> workflowSnapshotsWithFieldUpdates {get;set;}

	public CollectWorkflowRuleBatch(id currentSnapShotId, string sessionId) {
		snapShotId = currentSnapShotId;
		ssnId = sessionId;
		service = new MetadataService.MetadataPort();
		system.debug(logginglevel.ERROR, '*****service.endpoint_x=' + service.endpoint_x);
		if (service.endpoint_x.startsWithIgnoreCase('http:')) {
			service.endpoint_x = service.endpoint_x.removeStartIgnoreCase('http');
			service.endpoint_x = 'https' + service.endpoint_x;
		}
		service.SessionHeader = new MetadataService.SessionHeader_element();
		service.SessionHeader.sessionId = sessionId;
		List<MetadataService.ListMetadataQuery> queries = new List<MetadataService.ListMetadataQuery>();
		MetadataService.ListMetadataQuery currentQuery = new MetadataService.ListMetadataQuery();
		currentQuery.type_x = 'WorkflowRule';
		queries.add(currentQuery);
		MetadataService.FileProperties[] fileProperties = service.listMetadata(queries, 30);
		filePropertiesMap = new map<String, MetadataService.FileProperties>();
		fullnameList = new list<String>();
		if(fileProperties != null){
			for (MetadataService.FileProperties fileProperty : fileProperties) {
				filePropertiesMap.put(fileProperty.fullName, fileProperty);
				fullnameList.add(fileProperty.fullName);
			}
		}			
	}

	public Iterable<String> start(Database.BatchableContext BC) {
		return fullnameList;
	}

	public void execute(Database.BatchableContext BC, List<String> fullnameList) {
		MetadataService.IReadResult result = service.readMetadata('WorkflowRule', fullnameList);
		readResult.add(result);
	}

	public void finish(Database.BatchableContext BC) {
		list<Item_Snapshot__c> itsnList = new list<Item_Snapshot__c>();
		workflowSnapshotsWithFieldUpdates = new list<Item_Snapshot__c>();
		for (MetadataService.IReadResult result : readResult) {
			for (MetadataService.Metadata rules : result.getRecords()) {
				MetadataService.WorkflowRule rule = (MetadataService.WorkflowRule) rules;
				MetadataService.FileProperties fileProperty = filePropertiesMap.get(rule.fullName);
				Item_Snapshot__c itsn = new Item_Snapshot__c();
				itsn.Active__c = rule.active;
				itsn.Description__c = rule.description;
				itsn.Object__c = rule.fullName.substringBefore('.');
				itsn.Name = fileProperty.fullName.substringAfter('.').replace('_', ' ').left(80);
				itsn.Item_Full_Name__c = fileProperty.fullName.substringAfter('.').replace('_', ' ');
				itsn.Evaluation_Criteria__c = rule.triggerType;
				if (rule.criteriaItems == null) {
					itsn.Filter_or_Formula__c = 'Formula';
				} else {
					itsn.Filter_or_Formula__c = 'Filter';
				}
				if (rule.criteriaItems != null) {
					integer i = 1;
					itsn.Filter_Criteria__c = '';
					for (MetadataService.FilterItem fi : rule.criteriaItems) {
						itsn.Filter_Criteria__c += i + ' - ' + fi.field + ' ' + fi.operation + ' ';
						if (fi.valueField != null) {
							itsn.Filter_Criteria__c += fi.valueField;
						} else {
							itsn.Filter_Criteria__c += fi.value;
						}
						itsn.Filter_Criteria__c += ' \n';
						i++;
					}
					if (rule.booleanFilter != null) {
						itsn.Filter_Logic__c = rule.booleanFilter;
					}
				}
				if (rule.formula != null) {
					itsn.Rule_Criteria_Formula__c = rule.formula;
				}
				if(rule.actions != null){
					itsn.Workflow_Action_Name_Type__c = '';
					for(MetadataService.WorkflowActionReference wfar : rule.actions){
						itsn.Workflow_Action_Name_Type__c += itsn.Object__c + '.' + wfar.name + '|';
					}
				}
				itsn.Created_By__c = fileProperty.CreatedById;
				itsn.Created_Date__c = fileProperty.CreatedDate;
				itsn.Last_Modified_Date__c = fileProperty.lastModifiedDate;
				itsn.Last_Modified_By__c = fileProperty.lastModifiedById;
				itsn.Object_Id__c = fileProperty.id;
				itsn.System_Snapshot__c = snapShotId;
				itsn.Type__c = 'Workflow Rule';
				itsnList.add(itsn);
				if(rule.actions != null){
					for(MetadataService.WorkflowActionReference wfar : rule.actions){
						if(wfar.type_x == 'FieldUpdate'){
							workflowSnapshotsWithFieldUpdates.add(itsn);
						}
					}
				}
			}
		}
		Try{
			insert itsnList;
			ID workflowAlertJob = System.enqueueJob(new CollectWorkflowFieldUpdateQueueable(ssnId,itsnList));
		}
		Catch(exception e){
			system.debug(logginglevel.info, '*****'+e);
		}
	}

}