force-app/main/default/objects/Item_Snapshot__c/Item_Snapshot__c.object-meta.xml
<CustomObject>
    <label>Item Snapshot</label>
    <nameField>
        <label>Item Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_Snapshot__c/fields/System_Snapshot__c.field-meta.xml
<CustomField>
    <fullName>System_Snapshot__c</fullName>
    <label>System Snapshot</label>
    <referenceTo>System_Snapshot__c</referenceTo>
    <relationshipLabel>Item Snapshots</relationshipLabel>
    <relationshipName>Item_Snapshots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/System_Snapshot__c/System_Snapshot__c.object-meta.xml
<CustomObject>
    <label>System Snapshot</label>
    <nameField>
        <displayFormat>SysSnap - {000000}</displayFormat>
        <label>System Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Snapshot__c/fields/Time_Snapshot_Started__c.field-meta.xml
<CustomField>
    <fullName>Time_Snapshot_Started__c</fullName>
    <label>Time Snapshot Started</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/StartCollectingData.cls
public with sharing class StartCollectingData {

	public System_Snapshot__c currentSnapShot {get;set;}
	list<Item_Snapshot__c> itemSnapshotsToInsert {get;set;}
	list<Item_Snapshot__c> itemSnapshotsNeedingAttachments {get;set;}

	//creates the system snapshot in the variable called currentSnapShot
	public StartCollectingData() {
		currentSnapShot = new System_Snapshot__c(Time_Snapshot_Started__c = datetime.now());
	}

	public StartCollectingData(ApexPages.StandardController controller) {
		currentSnapShot = new System_Snapshot__c(Time_Snapshot_Started__c = datetime.now());
	}

	//collects the item snapshots
	public Void CollectItemSnapshots(){
		itemSnapshotsToInsert = new list<Item_Snapshot__c>();
		itemSnapshotsNeedingAttachments = new list<Item_Snapshot__c>();
		list<Item_Snapshot__c> allItemSnapshotList = new list<Item_Snapshot__c>();
		insert currentSnapShot;
		//collect Apex classes
			ID apexJob = System.enqueueJob(new CollectApexQueueable(currentSnapShot.id, UserInfo.getSessionId()));
			//list<Item_Snapshot__c> apexClassSnapShotList = CollectApexInfo.StartApexCollection(currentSnapShot.id);
			//allItemSnapshotList.addall(apexClassSnapShotList);
		//collect objects
			ID objectJob = System.enqueueJob(new CollectObjectsQueueable(currentSnapShot.id, UserInfo.getSessionId()));
			//list<Item_Snapshot__c> sobjectSnapShotList = CollectObjects.StartObjectCollection(currentSnapShot.id);
			//allItemSnapshotList.addall(sobjectSnapShotList);
		//collect Validation rules these are finished and inserted by the batch process they are not returned.
			ID validationRuleJob = System.enqueueJob(new CollectValidationRulesQueueable(currentSnapShot.id, UserInfo.getSessionId()));
		//collect Triggers		
			ID triggerJob = System.enqueueJob(new CollectApexTriggersQueueable(currentSnapShot.id, UserInfo.getSessionId()));
			//list<Item_Snapshot__c> apexTriggerSnapShotList = CollectApexTriggers.StartApexCollection(currentSnapShot.id);
			//allItemSnapshotList.addall(apexTriggerSnapShotList);
		//collect Workflow rules these are finished and inserted by the batch process they are not returned.
			/*
			This method stacks a number of different queueable and batch classes together.  Here is the order:
			CollectWorkflowRuleQueueable -> CollectWorkflowRuleBatch -> 
			CollectWorkflowFieldUpdateQueueable -> CollectWorkflowFieldUpdateBatch -> 
			CollectWorkflowTaskQueueable -> CollectWorkflowTaskBatch -> 
			CollectWorkflowEmailAlertQueueable -> CollectWorkflowEmailAlertBatch
			*/
			ID workflowRuleJob = System.enqueueJob(new CollectWorkflowRuleQueueable(currentSnapShot.id, UserInfo.getSessionId()));
		//Collect flow and process builder information.
			ID flowStartQueable = System.enqueueJob(new CollectFlowStart(currentSnapShot.id, UserInfo.getSessionId()));
			
	}




}