force-app/main/default/objects/Account/fields/Account_Region__c.field-meta.xml
<CustomField>
    <fullName>Account_Region__c</fullName>
    <inlineHelpText>This is the region of the account owner</inlineHelpText>
    <label>Account Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APAC - Independents</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
        <label>APAC - Japan</label>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
        <label>APAC - New Zealand</label>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
        <label>APAC - NSW</label>
    </customValue>
    <customValue>
        <fullName>APAC - QLD</fullName>
    </customValue>
    <customValue>
        <fullName>APAC - SA</fullName>
    </customValue>
    <customValue>
        <fullName>APAC_South East Asia</fullName>
        <label>APAC - South East Asia</label>
    </customValue>
    <customValue>
        <fullName>VIC</fullName>
        <label>APAC - VIC</label>
    </customValue>
    <customValue>
        <fullName>APAC - WA</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - France</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Germany</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - International</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Italy</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Nordics</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Poland</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Spain</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - UK</fullName>
    </customValue>
    <customValue>
        <fullName>LATAM</fullName>
    </customValue>
    <customValue>
        <fullName>US - Central</fullName>
    </customValue>
    <customValue>
        <fullName>US - East</fullName>
    </customValue>
    <customValue>
        <fullName>US - West</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <customValue>
        <fullName>EMEA - Switzerland</fullName>
        <isActive>false</isActive>
        <label>EMEA - Switzerland</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TDGAccountTriggerHandlerTest.cls
@isTest
public class TDGAccountTriggerHandlerTest {
    @isTest
    static void testUpdateRegion() {
        User u = new User(ID = UserInfo.getUserId(), User_Region__c = 'US - West');
        update u;
        User billingIntegrationUser= [SELECT ID FROM User WHERE Name='Billing Integrations'];

        Test.startTest();
        Account acc = new Account(Name = 'Test');
        insert acc;
        
        Id billingEntityRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Label.Billing_Entity_Record_Type).getRecordTypeId();
        Account acc2 = new Account(Name = 'Test2',RecordTypeId=billingEntityRecordTypeId,Account_Region__c='EMEA - Belgium');
        insert acc2;
        Test.stopTest();
        
        acc = [select Id, Account_Region__c from Account where Id = :acc.Id];
        System.assertEquals('US - West', acc.Account_Region__c);
        update acc;
        System.assertEquals('US - West', acc.Account_Region__c);
        
        acc2 = [select Id, Account_Region__c from Account where Id = :acc2.Id];
        System.assertEquals('US - West', acc2.Account_Region__c);
        update acc2;
        System.assertEquals('US - West', acc2.Account_Region__c);
        
        System.runAs(billingIntegrationUser){
            Account acc3 = new Account(Name='Test 3',RecordTypeId=billingEntityRecordTypeId,Account_Region__c= 'EMEA - Netherlands');
            insert acc3;
            acc3 = [select Id, Account_Region__c from Account where Id = :acc3.Id];
            System.assertEquals('EMEA - Netherlands', acc3.Account_Region__c);
        }
    }
}