force-app/main/default/objects/Account/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <label>Campaign</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If the Account Manager field is entered, show the manager of that Account. Otherwise show the error message</description>
    <label>Account Manager</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Account Manager</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agency_Name__c.field-meta.xml
<CustomField>
    <fullName>Agency_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>If the Agency Name field is entered, show the name of that Agency. Otherwise, show the error message.</description>
    <inlineHelpText>Enter the Agency Account facilitating the campaign, if applicable.  Do not include Brand direct accounts in this field</inlineHelpText>
    <label>Agency Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Advertising</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agency Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>If the Channel is selected, show the channel of that opportunity. Otherwise show the error message</description>
    <inlineHelpText>Publisher option is for Publisher-channel deals not Publisher deals</inlineHelpText>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Programmatic</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Publisher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DSP__c.field-meta.xml
<CustomField>
    <fullName>DSP__c</fullName>
    <label>DSP</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Channel__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A9</fullName>
            </value>
            <value>
                <fullName>AcuityAds</fullName>
            </value>
            <value>
                <fullName>Adelphic</fullName>
            </value>
            <value>
                <fullName>Adelphic/Viant</fullName>
            </value>
            <value>
                <fullName>Adform</fullName>
            </value>
            <value>
                <fullName>Adobe</fullName>
            </value>
            <value>
                <fullName>Amazon</fullName>
            </value>
            <value>
                <fullName>Amobee</fullName>
            </value>
            <value>
                <fullName>Beeswax</fullName>
            </value>
            <value>
                <fullName>Blis</fullName>
            </value>
            <value>
                <fullName>Centro</fullName>
            </value>
            <value>
                <fullName>DataXu</fullName>
            </value>
            <value>
                <fullName>DeepIntent</fullName>
            </value>
            <value>
                <fullName>DV360</fullName>
            </value>
            <value>
                <fullName>DBM</fullName>
                <label>Google DV360</label>
            </value>
            <value>
                <fullName>Hawk</fullName>
            </value>
            <value>
                <fullName>MarketOne</fullName>
            </value>
            <value>
                <fullName>MediaMath</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>PulsePoint</fullName>
            </value>
            <value>
                <fullName>Quantcast</fullName>
            </value>
            <value>
                <fullName>Stackadapt</fullName>
            </value>
            <value>
                <fullName>Supership</fullName>
            </value>
            <value>
                <fullName>TheTradeDesk</fullName>
            </value>
            <value>
                <fullName>Undertone</fullName>
            </value>
            <value>
                <fullName>Walmart DSP</fullName>
            </value>
            <value>
                <fullName>AppNexus</fullName>
                <label>Xandr</label>
            </value>
            <value>
                <fullName>Yahoo</fullName>
            </value>
            <value>
                <fullName>Zeta DSP</fullName>
            </value>
            <value>
                <fullName>Verizon Media</fullName>
                <isActive>false</isActive>
                <label>Verizon Media</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Date2__c.field-meta.xml
<CustomField>
    <fullName>End_Date2__c</fullName>
    <description>Contract End Date will automatically reflect the latest schedule date from the Products tab</description>
    <label>Contract End Date</label>
    <summarizedField>OpportunityLineItem.End_Date__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Exception_Approval__c.field-meta.xml
<CustomField>
    <fullName>Exception_Approval__c</fullName>
    <description>This field displays the exception status</description>
    <label>Exception Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Exception</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Exception Rejected</fullName>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Exception Approved</fullName>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Requires Re-submission</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Expediting_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Expediting_Approval_Status__c</fullName>
    <description>This field displays the expedite status</description>
    <label>Expedite Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Net_Total_Ordered_Amount_1__c.field-meta.xml
<CustomField>
    <fullName>Net_Total_Ordered_Amount_1__c</fullName>
    <description>SOP-3122</description>
    <label>Gross Total Ordered Amount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Region__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Region__c</fullName>
    <description>This is the Region of the Sales Rep who owns the opportunity (Opportunity Owner) region.  A trigger updates this value when the record is created or the opportunity owner changes.</description>
    <inlineHelpText>This is the Region of the Sales Rep who owns the opportunity (Opportunity Owner) region.</inlineHelpText>
    <label>Opportunity Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date2__c.field-meta.xml
<CustomField>
    <fullName>Start_Date2__c</fullName>
    <description>Roll up from product for the earliest start date.</description>
    <inlineHelpText>Contract Start Date will automatically reflect the earliest schedule date from the Products tab</inlineHelpText>
    <label>Contract Start Date</label>
    <summarizedField>OpportunityLineItem.Start_Date__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APAC - Independents</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
        <label>APAC - Japan</label>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
        <label>APAC - New Zealand</label>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
        <label>APAC - NSW</label>
    </customValue>
    <customValue>
        <fullName>APAC - QLD</fullName>
    </customValue>
    <customValue>
        <fullName>APAC - SA</fullName>
    </customValue>
    <customValue>
        <fullName>APAC_South East Asia</fullName>
        <label>APAC - South East Asia</label>
    </customValue>
    <customValue>
        <fullName>VIC</fullName>
        <label>APAC - VIC</label>
    </customValue>
    <customValue>
        <fullName>APAC - WA</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - France</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Germany</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - International</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Italy</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Nordics</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Poland</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Spain</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - UK</fullName>
    </customValue>
    <customValue>
        <fullName>LATAM</fullName>
    </customValue>
    <customValue>
        <fullName>US - Central</fullName>
    </customValue>
    <customValue>
        <fullName>US - East</fullName>
    </customValue>
    <customValue>
        <fullName>US - West</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <customValue>
        <fullName>EMEA - Switzerland</fullName>
        <isActive>false</isActive>
        <label>EMEA - Switzerland</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FieldsWrapperNA.cls
public class FieldsWrapperNA {
    
    public Fields fields { get; set; }
    
    public class Fields {
        public Project project { get; set; } // Project
        public String summary { get; set; } //Summary
        public IssueType issuetype { get; set; } //Issue Type
        public String customfield_13403 { get; set; } // Campaign Name or Opportunity Name
        public CustomField assignee { get; set; } // Assignee
        public Reporter reporter { get; set; } // Reporter
        public String customfield_11860 { get; set; } // Agency - Agency Name
        public String customfield_11861{ get; set; }// Advertiser - Account Name
        public CustomFieldOption customfield_13301{ get; set;}// Campaign Type - Channel
        public String customfield_11874 { get; set; }// Salesfore Link
        public String customfield_13910 { get; set; }// Salesforce Id
        public List<CustomFieldOption> customfield_14016 { get; set; }// DSP
        public CustomFieldOption customfield_13592{ get; set;}// Has the campaign been approved to be expedited? 
        public String customfield_13590 { get; set; }// Campaign Start Date
        public String customfield_13591 { get; set; }// Campaign End Date  
        public CustomFieldOption customfield_13534{ get; set;}// Currency(*)
        public Decimal customfield_13400 { get; set; }//Campaign Value - Total Ordered Amount
    }
    
    public class Project {
        public String key { get; set; }
    }

    public class CustomField {
        public String id { get; set; }
    }
    
    public class Reporter {
        public String id { get; set; }
    }
    
    public class CustomFieldOption {
        public String value { get; set; }
    }
    
    public class CustomFieldDoc {
        public Integer version { get; set; }
        public String type { get; set; }
        public List<DocContent> content { get; set; }
    }
    
    public class DocContent {
        public String type { get; set; }
        public List<ContentText> content { get; set; }
    }
    
    public class ContentText {
        public String type { get; set; }
        public String text { get; set; }
    }
    
    public class IssueType {
        public String name { get; set; }
    }
    
    public FieldsWrapperNA createJiraPostBody(Id oppId,String flowUserEmail){ 
        
        system.debug('CPU Time before NA JIRA BODY  '+Limits.getCpuTime());
        Opportunity opp = [SELECT Id,Name,Account.Name,Agency_Name__r.Name,
                           Exception_Approval__c,Start_Date2__c,End_Date2__c,
                           currencyIsoCode,Net_Total_Ordered_Amount_1__c,
                           Opportunity_Region__c,Owner.Email,Account_Manager__r.Email,
                           Expediting_Approval_Status__c,Amount,Channel__c,DSP__c  from Opportunity WHERE Id=:oppId];
        system.debug('CPU Time after query  '+Limits.getCpuTime());
        String sellerNameJiraId = JiraUserClass.getJiraUser(opp.Account_Manager__r.Email);
        system.debug('CPU Time after 1 user call  '+Limits.getCpuTime());
        String assigneeNameJiraId = JiraUserClass.getJiraUser(flowUserEmail);
        system.debug('CPU Time after 2 user call  '+Limits.getCpuTime());
        
        FieldsWrapperNA wrapper = new FieldsWrapperNA();
        wrapper.fields = new FieldsWrapperNA.Fields();
        
        //Assigning the Project
        wrapper.fields.project = new FieldsWrapperNA.Project();
        wrapper.fields.project.key = 'AC'; 
        
        //Assignee
        wrapper.fields.assignee = new FieldsWrapperNA.CustomField() ;
        wrapper.fields.assignee.id = assigneeNameJiraId; 
        
        //Reporter
        wrapper.fields.reporter = new FieldsWrapperNA.Reporter();
        wrapper.fields.reporter.id = sellerNameJiraId;
        
         //Assigning the Opportunty Name
        wrapper.fields.customfield_13403 = opp.Name;

        //Account Name - Advertiser Name
        wrapper.fields.customfield_11861 = opp.Account.Name;
        
        //Agency Name - Agency
        system.debug('Agency Name --------' + opp.Agency_Name__r.Name);   
        wrapper.fields.customfield_11860 = opp.Agency_Name__r.Name;
        //Campaign Type - Channel
        wrapper.fields.customfield_11860 = opp.Channel__c;
        
        //Salesforce Link
        wrapper.fields.customfield_11874 = Label.OpportunityURL+opp.Id+'/view'; 
        
          //Salesforce Id
        wrapper.fields.customfield_13910 = opp.Id;
        
        //Expedite Approval Status - Rejected - No, Approved - Yes
        wrapper.fields.customfield_13592 = new FieldsWrapperNA.CustomFieldOption();
        if(opp.Expediting_Approval_Status__c == 'Approved'){
            wrapper.fields.customfield_13592.value = 'Yes';
        }else{
            wrapper.fields.customfield_13592.value = 'No';
        }

        
        //DSP - From the Custom Metadata SF_Jira_DSP_Map__mdt 
        wrapper.fields.customfield_14016 = new List<FieldsWrapperNA.CustomFieldOption>();
        FieldsWrapperNA.CustomFieldOption option2 = new FieldsWrapperNA.CustomFieldOption();
        
        /*Map<String,String> sfDsp2JiraDsp = new Map<String,String>{'Adelphic/Viant'=>'Adelphic',
            'Adobe'=>'Adobe',
            'Amobee'=>'Amobee',
            'DBM'=>'Google DV360',
            'MediaMath'=>'MediaMath',
            'PulsePoint'=>'PulsePoint',
            'Supership'=>'Supership (JP)',
            'TheTradeDesk'=>'theTradeDesk',
            'AppNexus'=>'Xandr'
            };*/
        Map<String,String> sfDsp2JiraDsp = new Map<String,String>();
        for(SF_Jira_DSP_Map__mdt sfJiraDspMdt: SF_Jira_DSP_Map__mdt.getAll().values()){
            sfDsp2JiraDsp.put(sfJiraDspMdt.DSP_SF__c,sfJiraDspMdt.DSP_Jira__c );		
        }
        
        if(opp.DSP__c!=null){
            system.debug(opp.DSP__c);
            if(sfDsp2JiraDsp.containsKey(opp.DSP__c)){
                option2.value = sfDsp2JiraDsp.get(opp.DSP__c);
                wrapper.fields.customfield_14016.add(option2);
            }
        }        
        
        
        //Start Date
        if(opp.Start_Date2__c!=null){
            wrapper.fields.customfield_13590 = String.valueOf(opp.Start_Date2__c);
        }else{
            wrapper.fields.customfield_13590 = '2020-01-01';
        } 
        
        //End Date
        if(opp.End_Date2__c!=null){
            wrapper.fields.customfield_13591 = String.valueOf(opp.End_Date2__c);
        }else{
            wrapper.fields.customfield_13591 = '2020-01-01';
        }
        
        //Opportunity Currency
        wrapper.fields.customfield_13534 = new FieldsWrapperNA.CustomFieldOption();
        wrapper.fields.customfield_13534.value = opp.CurrencyIsoCode;
        
        //Net Total Ordered Amount
        wrapper.fields.customfield_13400 = opp.Amount;
           
        //Summary
        wrapper.fields.summary = opp.Name;
        
        //Issue Type
        wrapper.fields.issuetype = new FieldsWrapperNA.IssueType();
        wrapper.fields.issuetype.name = 'Ad Campaign';
        
        System.debug(wrapper);
        system.debug('CPU Time after NA JIRA BODY  '+Limits.getCpuTime());
        return wrapper;
    }
}