force-app/main/default/objects/Account/fields/Account_Region__c.field-meta.xml
<CustomField>
    <fullName>Account_Region__c</fullName>
    <inlineHelpText>This is the region of the account owner</inlineHelpText>
    <label>Account Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Only_Agency_Open_and_Won_Opp_Count__c.field-meta.xml
<CustomField>
    <fullName>Only_Agency_Open_and_Won_Opp_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Agency Opportunity Open and Won Count of record types (Advertising, Verity, Open Market)</description>
    <inlineHelpText>Agency Opportunity Open and Won Count of record types (Advertising, Verity, Open Market)</inlineHelpText>
    <label>Agency Open and Won Opp Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Only_Agency_Open_Opp_Count__c.field-meta.xml
<CustomField>
    <fullName>Only_Agency_Open_Opp_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Agency Opportunity Open Count of record types (Advertising, Verity, Open Market)</description>
    <inlineHelpText>Agency Opportunity Open Count of record types (Advertising, Verity, Open Market)</inlineHelpText>
    <label>Agency Open Opp Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Only_Agency_Opp_Count__c.field-meta.xml
<CustomField>
    <fullName>Only_Agency_Opp_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Agency Opportunity Total Count of record types (Advertising, Activation, Playground Attention Intelligence Platform, Open Market, Verity, Video)</description>
    <inlineHelpText>Agency Opportunity Total Count of record types (Advertising, Activation, Playground Attention Intelligence Platform, Open Market, Verity, Video)</inlineHelpText>
    <label>Agency Opp Total Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Only_Agency_Opp_Won_Count__c.field-meta.xml
<CustomField>
    <fullName>Only_Agency_Opp_Won_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Agency Opportunity Won  Count of record types (Advertising, Activation, Playground Attention Intelligence Platform, Open Market, Verity, Video)</description>
    <inlineHelpText>Agency Opportunity Won Count of record types (Advertising, Activation, Playground Attention Intelligence Platform, Open Market, Verity, Video)</inlineHelpText>
    <label>Agency Opp Won Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Agency_Name__c.field-meta.xml
<CustomField>
    <fullName>Agency_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>If the Agency Name field is entered, show the name of that Agency. Otherwise, show the error message.</description>
    <inlineHelpText>Enter the Agency Account facilitating the campaign, if applicable.  Do not include Brand direct accounts in this field</inlineHelpText>
    <label>Agency Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Advertising</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agency Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Enter in the End date of the campaign</description>
    <inlineHelpText>To edit this date, simply ensure that the product end dates are correct. This field will reflect the latest end date of the products.</inlineHelpText>
    <label>End Date (old)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_KPI__c.field-meta.xml
<CustomField>
    <fullName>Primary_KPI__c</fullName>
    <label>Primary KPI</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Action Rate</fullName>
            </value>
            <value>
                <fullName>App Download</fullName>
            </value>
            <value>
                <fullName>Attention</fullName>
            </value>
            <value>
                <fullName>Attention Time</fullName>
            </value>
            <value>
                <fullName>Brand Awareness Lift</fullName>
            </value>
            <value>
                <fullName>Conversions</fullName>
            </value>
            <value>
                <fullName>Cost Efficiency</fullName>
            </value>
            <value>
                <fullName>CPA</fullName>
            </value>
            <value>
                <fullName>CPC</fullName>
            </value>
            <value>
                <fullName>CPCV</fullName>
            </value>
            <value>
                <fullName>CPM</fullName>
            </value>
            <value>
                <fullName>CPQA</fullName>
            </value>
            <value>
                <fullName>CTR</fullName>
            </value>
            <value>
                <fullName>Engagement</fullName>
            </value>
            <value>
                <fullName>Foot Traffic</fullName>
            </value>
            <value>
                <fullName>In-Store Sales</fullName>
            </value>
            <value>
                <fullName>Landing Page Yield</fullName>
            </value>
            <value>
                <fullName>Lead Generation</fullName>
            </value>
            <value>
                <fullName>Online Sales</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Play Rate</fullName>
            </value>
            <value>
                <fullName>Reach</fullName>
            </value>
            <value>
                <fullName>ROAS</fullName>
            </value>
            <value>
                <fullName>Sales/Consideration Lift</fullName>
            </value>
            <value>
                <fullName>Shopping Cart Volume</fullName>
            </value>
            <value>
                <fullName>Site Traffic</fullName>
            </value>
            <value>
                <fullName>Traffic Rate</fullName>
            </value>
            <value>
                <fullName>VCR</fullName>
            </value>
            <value>
                <fullName>Video Views</fullName>
            </value>
            <value>
                <fullName>Viewability</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SalesLoft1__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>SalesLoft1__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary Contact Associated with Opportunity.</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Primary Contact</relationshipLabel>
    <relationshipName>Opportunity_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Enter in day campaign starts</description>
    <inlineHelpText>To edit this date, simply ensure that the product start dates are correct.  This field will reflect the earliest start date of the products.</inlineHelpText>
    <label>Start Date (old)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Verity_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Verity_Revenue__c</fullName>
    <label>Verity Revenue</label>
    <summarizedField>OpportunityLineItem.Verity_Revenue__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Voiced_Budget__c.field-meta.xml
<CustomField>
    <fullName>Voiced_Budget__c</fullName>
    <description>Enter Voiced Budget for programmatic opportunities.</description>
    <inlineHelpText>This field contains 100% of spend before fees, data, etc. (i.e. what the client is willing to spend overall).</inlineHelpText>
    <label>Voiced Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Verity.recordType-meta.xml
<RecordType>
    <fullName>Verity</fullName>
    <active>true</active>
    <businessProcess>Verity</businessProcess>
    <label>Verity</label>
</RecordType>

force-app/main/default/objects/Trigger_Setting__c/Trigger_Setting__c.object-meta.xml
<CustomObject>
    <description>This object control type of operation in each object</description>
    <label>Trigger Setting</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Setting__c/fields/After_Delete__c.field-meta.xml
<CustomField>
    <fullName>After_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/fields/After_Insert__c.field-meta.xml
<CustomField>
    <fullName>After_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/fields/After_Update__c.field-meta.xml
<CustomField>
    <fullName>After_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/fields/Before_Delete__c.field-meta.xml
<CustomField>
    <fullName>Before_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/fields/Prevent_Recursion__c.field-meta.xml
<CustomField>
    <fullName>Prevent_Recursion__c</fullName>
    <label>Prevent Recursion</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APAC - Independents</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
        <label>APAC - Japan</label>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
        <label>APAC - New Zealand</label>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
        <label>APAC - NSW</label>
    </customValue>
    <customValue>
        <fullName>APAC - QLD</fullName>
    </customValue>
    <customValue>
        <fullName>APAC - SA</fullName>
    </customValue>
    <customValue>
        <fullName>APAC_South East Asia</fullName>
        <label>APAC - South East Asia</label>
    </customValue>
    <customValue>
        <fullName>VIC</fullName>
        <label>APAC - VIC</label>
    </customValue>
    <customValue>
        <fullName>APAC - WA</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - France</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Germany</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - International</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Italy</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Nordics</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Poland</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Spain</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - UK</fullName>
    </customValue>
    <customValue>
        <fullName>LATAM</fullName>
    </customValue>
    <customValue>
        <fullName>US - Central</fullName>
    </customValue>
    <customValue>
        <fullName>US - East</fullName>
    </customValue>
    <customValue>
        <fullName>US - West</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <customValue>
        <fullName>EMEA - Switzerland</fullName>
        <isActive>false</isActive>
        <label>EMEA - Switzerland</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityTriggerHandlerNewTest2.cls
@isTest
public class OpportunityTriggerHandlerNewTest2 {
    @testSetup
    static void testData(){
        Trigger_Setting__c tsOppConRole = new Trigger_Setting__c();
        tsOppConRole.Object_Name__c   = 'OpportunityContactRole';
        tsOppConRole.After_Insert__c = true;
        tsOppConRole.After_Update__c = true;
        tsOppConRole.Before_Delete__c = true;
        tsOppConRole.Prevent_Recursion__c = 'isPrimary';
        tsOppConRole.Name             = 'Opportunity Contact Role';
        insert tsOppConRole;
        List<Account> accList = new List<Account>();
        for(Integer i=0;i<2;i++){
            Account acc = new Account();
            acc.Name = 'Test'+i;
            acc.Type = '3rd Party Supplier';
            acc.Account_Region__c = 'US - Central';
            acc.Industry = 'Automotive';
            accList.add(acc);
        }
        insert accList;
        List<Contact> conList = new List<Contact>();
        Contact con1 = new Contact(lastName='Test');
        Contact con2 = new Contact(lastName = 'Test2');
        conList.add(con1);
        conList.add(con2);
        insert conList;
        List<Opportunity> oppList = new List<Opportunity>();
        for(Account acc: accList){
            for(Integer i=0;i<10;i++){
                 Opportunity opp1 = new Opportunity(AccountId= acc.id,Agency_Name__c=acc.id,
                                           Start_Date__c = System.Today(),
                                           End_Date__c =System.Today()+ 100,
                                           name = acc.Name + 'i',
                                           CloseDate= System.Today()+ 3,
                                           SalesLoft1__Primary_Contact__c = conList[0].Id,
                                           Primary_KPI__c='Action Rate',
                                          // Why_GumGum__c='Attention',
                                           Amount=500,
                                           //Business_Objective__c = 'Acquire new customers',         
                                           StageName = (i==2?'Closed/Lost':'Initial call')); 
                oppList.add(opp1);
            }
        }
        insert oppList;
    }
    @isTest
    public static void method1(){
        List<Account> accList = [SELECT id,Only_Agency_Opp_Count__c FROM Account];
        system.assertEquals(10, accList[0].Only_Agency_Opp_Count__c);
        List<Opportunity> oppList = [SELECT Id,stageName,AccountId,Agency_Name__c FROM Opportunity WHERE Agency_Name__c = :accList[0].Id AND stageName='Initial call'];
        system.assertEquals(9, oppList.size());
        oppList[0].Agency_Name__c = accList[1].Id;
        oppList[1].stageName = 'Closed/Lost';
        oppList[1].Amount = 1000;
        update oppList;
        List<Account> accList2 = [SELECT Id,Only_Agency_Opp_Count__c,Only_Agency_Opp_Won_Count__c,Only_Agency_Open_Opp_Count__c,Only_Agency_Open_and_Won_Opp_Count__c FROM Account WHERE Id=:accList[0].Id OR Id = :accList[1].Id];
        system.assertEquals(9,accList2[0].Only_Agency_Opp_Count__c);
        system.assertEquals(7, accList2[0].Only_Agency_Open_Opp_Count__c);
        system.assertEquals(10, accList2[1].Only_Agency_Open_Opp_Count__c);
        system.assertEquals(11,accList2[1].Only_Agency_Opp_Count__c);
    }
    
     @isTest
    static void method2(){
        Trigger_Setting__c tsOppLineItem = new Trigger_Setting__c();
        tsOppLineItem.Object_Name__c   = 'OpportunityLineItem';
        tsOppLineItem.After_Insert__c = true;
        tsOppLineItem.After_Update__c = true;
        tsOppLineItem.After_Delete__c = true;
        tsOppLineItem.Name             = 'OpportunityLineItem'; 
        insert tsOppLineItem;
        
        Account testAcc = new Account(name = 'TestAcc');
        insert testAcc;
        
        Contact con2 = new Contact(lastName = 'Test2',AccountId=testAcc.ID);
        
        Id RecordTypeIdOpp = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Verity - Demand').getRecordTypeId();
        
        Id pricebookId = Test.getStandardPricebookId();
        
        Product2 prd1 = new Product2 (Name='test product 1',Verity_Revenue__c=5,Description='Test Product Entry 1',productCode = 'ABC', isActive = true,CanUseQuantitySchedule =true,CanUseRevenueSchedule=true);
        insert prd1;
        
        PricebookEntry pbe1 = new PricebookEntry (Product2ID=prd1.id,Pricebook2ID=pricebookId,UnitPrice=50, isActive=true);
        insert pbe1;
        
        Opportunity opp = new Opportunity(AccountId= testAcc.id,SalesLoft1__Primary_Contact__c = con2.Id,
                                          Agency_Name__c=testAcc.id,Start_Date__c = System.Today(),End_Date__c =System.Today()+ 100 ,name = 'Test Opp',CloseDate= System.Today()+ 3 ,Pricebook2Id = pbe1.Pricebook2Id,RecordTypeId = RecordTypeIdOpp, StageName ='Opportunity Identified' );
        insert opp;
        
        opportunity getOpp = [SELECT ID,pricebook2Id from opportunity where Id = :opp.Id];
        getOpp.Pricebook2Id = pricebookId;
        update getOpp;
        
        OpportunityLineItem opl1 = new OpportunityLineItem(OpportunityId= opp.id,Start_Date__c =  System.Today().toStartOfMonth(),End_Date__c =System.Today().toStartOfMonth().addMonths(1),PriceBookEntryID=pbe1.id,Quantity=1,TotalPrice= 50,of_Budget__c=100 ) ;
        insert opl1;
        
        system.debug('oppPricebookId'+ [SELECT ID,pricebook2Id from opportunity where Id = :opp.Id].pricebook2Id);
        system.debug('Std PricebookId' + pricebookId);
        
        List<OpportunityLineItemSchedule> oliScheList = new List<OpportunityLineItemSchedule>();
        
        OpportunityLineItemSchedule oliSched = new OpportunityLineItemSchedule(
            OpportunityLineItemId = opl1.Id,
            Type = 'Both',
            Quantity = 2,
            Revenue = 200,Verity_Revenue__c = 10,Actual_Revenue_Verity__c = 100,
            ScheduleDate = System.Today().toStartOfMonth().addMonths(1)-1
        );
        oliScheList.add(oliSched);
        OpportunityLineItemSchedule oliSched2 = new OpportunityLineItemSchedule(
            OpportunityLineItemId = opl1.Id,
            Type = 'Both',
            Quantity = 2,
            Revenue = 200,Verity_Revenue__c = 10,Actual_Revenue_Verity__c = 100,
            ScheduleDate = System.Today().toStartOfMonth().addMonths(2)-1
        );
        oliScheList.add(oliSched2);
        insert oliScheList;
        
        oliScheList[0].Verity_Revenue__c = 90;
        oliScheList[0].Actual_Revenue_Verity__c = 200;
        update oliScheList;
        Test.startTest();
        opp.Voiced_Budget__c = 200;
        update opp;
        Test.stopTest();   
    }

}