force-app/main/default/objects/Account/fields/Account_Region__c.field-meta.xml
<CustomField>
    <fullName>Account_Region__c</fullName>
    <inlineHelpText>This is the region of the account owner</inlineHelpText>
    <label>Account Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <label>Supplier</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Agency_Name__c.field-meta.xml
<CustomField>
    <fullName>Agency_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>If the Agency Name field is entered, show the name of that Agency. Otherwise, show the error message.</description>
    <inlineHelpText>Enter the Agency Account facilitating the campaign, if applicable.  Do not include Brand direct accounts in this field</inlineHelpText>
    <label>Agency Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Advertising</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agency Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Enter in the End date of the campaign</description>
    <inlineHelpText>To edit this date, simply ensure that the product end dates are correct. This field will reflect the latest end date of the products.</inlineHelpText>
    <label>End Date (old)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SalesLoft1__Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>SalesLoft1__Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary Contact Associated with Opportunity.</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Primary Contact</relationshipLabel>
    <relationshipName>Opportunity_Primary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Enter in day campaign starts</description>
    <inlineHelpText>To edit this date, simply ensure that the product start dates are correct.  This field will reflect the earliest start date of the products.</inlineHelpText>
    <label>Start Date (old)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/Trigger_Setting__c.object-meta.xml
<CustomObject>
    <description>This object control type of operation in each object</description>
    <label>Trigger Setting</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Setting__c/fields/After_Insert__c.field-meta.xml
<CustomField>
    <fullName>After_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/fields/After_Update__c.field-meta.xml
<CustomField>
    <fullName>After_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/fields/Before_Delete__c.field-meta.xml
<CustomField>
    <fullName>Before_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/fields/Prevent_Recursion__c.field-meta.xml
<CustomField>
    <fullName>Prevent_Recursion__c</fullName>
    <label>Prevent Recursion</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APAC - Independents</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
        <label>APAC - Japan</label>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
        <label>APAC - New Zealand</label>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
        <label>APAC - NSW</label>
    </customValue>
    <customValue>
        <fullName>APAC - QLD</fullName>
    </customValue>
    <customValue>
        <fullName>APAC - SA</fullName>
    </customValue>
    <customValue>
        <fullName>APAC_South East Asia</fullName>
        <label>APAC - South East Asia</label>
    </customValue>
    <customValue>
        <fullName>VIC</fullName>
        <label>APAC - VIC</label>
    </customValue>
    <customValue>
        <fullName>APAC - WA</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - France</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Germany</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - International</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Italy</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Nordics</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Poland</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Spain</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - UK</fullName>
    </customValue>
    <customValue>
        <fullName>LATAM</fullName>
    </customValue>
    <customValue>
        <fullName>US - Central</fullName>
    </customValue>
    <customValue>
        <fullName>US - East</fullName>
    </customValue>
    <customValue>
        <fullName>US - West</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <customValue>
        <fullName>EMEA - Switzerland</fullName>
        <isActive>false</isActive>
        <label>EMEA - Switzerland</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityContactRoleTriggerHandlerTest.cls
/*
	Description	   : OpportunityContactRoleTriggerHandler test Class
	Created Date   : 09-12-2022
	Created By     : Kiran
	Change Request : 
*/
@isTest
public class OpportunityContactRoleTriggerHandlerTest {
    
    @testSetup
    public static void testData(){
        // Insert Trigger Settings for OpportunityContactRole
        Trigger_Setting__c tsOppConRole = new Trigger_Setting__c();
        tsOppConRole.Object_Name__c   = 'OpportunityContactRole';
        tsOppConRole.After_Insert__c = true;
        tsOppConRole.After_Update__c = true;
        tsOppConRole.Before_Delete__c = true;
        tsOppConRole.Prevent_Recursion__c = 'isPrimary';
        tsOppConRole.Name             = 'Opportunity Contact Role';
        insert tsOppConRole;
        //Inserting Account
        Account acc = new Account();
        acc.Name = 'Test';
        acc.Type = '3rd Party Supplier';
        acc.Account_Region__c = '	US - Central';
        acc.Industry = 'Automotive';
        insert acc;
        //Inserting Contacts
        List<Contact> conList = new List<Contact>();
        Contact con1 = new Contact(lastName='Test');
        Contact con2 = new Contact(lastName = 'Test2');
        conList.add(con1);
        conList.add(con2);
        insert conList;
        //Inserting Opportunity
        Opportunity opp1 = new Opportunity(AccountId= acc.id,Agency_Name__c=acc.id,
                                           Start_Date__c = System.Today(),
                                           End_Date__c =System.Today()+ 100,
                                           name = 'Test Opp1',
                                           SalesLoft1__Primary_Contact__c = conList[0].Id,
                                           CloseDate= System.Today()+ 3,
                                           StageName ='Initial call'); 
        insert opp1;
    }
    @isTest
    static void method1(){
        
        Opportunity opp = [SELECT Id,SalesLoft1__Primary_Contact__c FROM Opportunity LIMIT 1];
        List<Contact> conList = [SELECT Id FROM Contact];
        //Updating OpportunityContactRole(unchecking primary)
        OpportunityContactRole oppConRole = [SELECT Id,ContactId,OpportunityId,IsPrimary FROM OpportunityContactRole WHERE OpportunityId = :opp.Id AND IsPrimary=true LIMIT 1];
        oppConRole.IsPrimary = false;
        update oppConRole;
        
        Opportunity newOpp = [SELECT Id,SalesLoft1__Primary_Contact__c FROM Opportunity LIMIT 1];
        System.Assert(newOpp.SalesLoft1__Primary_Contact__c==null);
        
        //Inserting New Primary OpportunityContactRole
        OpportunityContactRole oppConRole2 = new OpportunityContactRole(OpportunityId=opp.Id,ContactId = conList[1].Id,IsPrimary=true);
        insert oppConRole2;
        
        Opportunity newOpp2 = [SELECT Id,SalesLoft1__Primary_Contact__c FROM Opportunity LIMIT 1];
        System.assertEquals(oppConRole2.contactId, newOpp2.SalesLoft1__Primary_Contact__c);
        
        //Changing the Primary OpportunityContactRole to other OpportunityContactRole
        OpportunityContactRole oppConRole3 = [SELECT Id,ContactId,OpportunityId,IsPrimary FROM OpportunityContactRole WHERE OpportunityId = :opp.Id AND IsPrimary=false LIMIT 1];
        oppConRole3.isPrimary = true;
        update oppConRole3;
        
        Opportunity newOpp3 = [SELECT Id,SalesLoft1__Primary_Contact__c FROM Opportunity LIMIT 1];
        System.assertEquals(oppConRole3.contactId, newOpp3.SalesLoft1__Primary_Contact__c); 
        
        //Trying to delete primary Contact
        Database.delete(oppConRole3,false);

    }
}