force-app/main/default/objects/Account/fields/Account_Owner_User_Region__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_User_Region__c</fullName>
    <formula>TEXT( Owner.User_Region__c )</formula>
    <label>Account Owner User Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Region__c.field-meta.xml
<CustomField>
    <fullName>Account_Region__c</fullName>
    <inlineHelpText>This is the region of the account owner</inlineHelpText>
    <label>Account Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/General_Setting__mdt/fields/Enable_TDG_Account_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Enable_TDG_Account_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable TDG Account Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APAC - Independents</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
        <label>APAC - Japan</label>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
        <label>APAC - New Zealand</label>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
        <label>APAC - NSW</label>
    </customValue>
    <customValue>
        <fullName>APAC - QLD</fullName>
    </customValue>
    <customValue>
        <fullName>APAC - SA</fullName>
    </customValue>
    <customValue>
        <fullName>APAC_South East Asia</fullName>
        <label>APAC - South East Asia</label>
    </customValue>
    <customValue>
        <fullName>VIC</fullName>
        <label>APAC - VIC</label>
    </customValue>
    <customValue>
        <fullName>APAC - WA</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - France</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Germany</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - International</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Italy</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Nordics</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Poland</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Spain</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - UK</fullName>
    </customValue>
    <customValue>
        <fullName>LATAM</fullName>
    </customValue>
    <customValue>
        <fullName>US - Central</fullName>
    </customValue>
    <customValue>
        <fullName>US - East</fullName>
    </customValue>
    <customValue>
        <fullName>US - West</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <customValue>
        <fullName>EMEA - Switzerland</fullName>
        <isActive>false</isActive>
        <label>EMEA - Switzerland</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TDGAccountTriggerHandler.cls
/*
Description       : TDGAccountTriggerHandler
Last Updated Date : 20-03-2023
Last Updated By   : Kiran
Change Request    : Skips the trigger if the Record Type is 'Billing Entity' and User = 'Billing Integrations'
*/
public class TDGAccountTriggerHandler {
    public static final String SETTING_NAME = Test.isRunningTest() ? 'TestContext' : 'Default';

    public void afterInsert(List<Account> newList) {
        updateRegion(newList, null);
    }

    public void afterUpdate(List<Account> newList, Map<ID, Account> oldMap) {
        updateRegion(newList, oldMap);
    }

    private void updateRegion(List<Account> newList, Map<ID, Account> oldMap) {
        if(!General_Setting__mdt.getInstance(SETTING_NAME).Enable_TDG_Account_Trigger__c) return; 
        List<Account> accsToProcess = new List<Account>();
        Id billingEntityRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Label.Billing_Entity_Record_Type).getRecordTypeId();
        for(Account acc : newList) {
            if(acc.RecordTypeId==billingEntityRecordTypeId && UserInfo.getUserId()==Label.Billing_Integration_UserId) continue;
            if(oldMap != null) {
                Account oldAcc = oldMap.get(acc.Id);
                if(acc.OwnerId == oldAcc.OwnerId) continue;
            }
            
            accsToProcess.add(new Account(
                ID = acc.Id,
                Account_Region__c = acc.Account_Owner_User_Region__c
            ));
        }

        if(accsToProcess.size() > 0) {
            update accsToProcess;
        }
    }
}