force-app/main/default/objects/General_Setting__mdt/fields/Enable_TDG_Opportunity_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Enable_TDG_Opportunity_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable TDG Opportunity Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Owner_Region__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner_Region__c</fullName>
    <description>&quot;Opportunity Region&quot; auto populates User Region based on the Account Owner&apos;s Region. It is derived from the picklist &quot;User Region&quot; which is a value in user settings required for every user and represents the Region that the sales rep/account manager is selling into, or alternatively the operations or other personnel&apos;s primary regional location. It is first converted to a text field &quot;User Region Desc&quot; and used in formulas to calculate the Account and Opportunity Region. Via Celigo integrator.io, the Opportunity Region is mapped to the Netsuite Customer Sales Order Subsidiary.</description>
    <formula>TEXT(Owner.User_Region__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field is a read-only formula. &quot;Opportunity Region&quot; auto populates based on the Opportunity Owner&apos;s Region. It is derived from the picklist &quot;User Region&quot; which is a value in user settings required for every user and represents the Region that the sales rep/account manager is selling into, or alternatively the operations or other personnel&apos;s primary regional location.</inlineHelpText>
    <label>Opportunity Owner Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Region__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Region__c</fullName>
    <description>This is the Region of the Sales Rep who owns the opportunity (Opportunity Owner) region.  A trigger updates this value when the record is created or the opportunity owner changes.</description>
    <inlineHelpText>This is the Region of the Sales Rep who owns the opportunity (Opportunity Owner) region.</inlineHelpText>
    <label>Opportunity Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>APAC - Independents</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
        <label>APAC - Japan</label>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
        <label>APAC - New Zealand</label>
    </customValue>
    <customValue>
        <fullName>NSW</fullName>
        <label>APAC - NSW</label>
    </customValue>
    <customValue>
        <fullName>APAC - QLD</fullName>
    </customValue>
    <customValue>
        <fullName>APAC - SA</fullName>
    </customValue>
    <customValue>
        <fullName>APAC_South East Asia</fullName>
        <label>APAC - South East Asia</label>
    </customValue>
    <customValue>
        <fullName>VIC</fullName>
        <label>APAC - VIC</label>
    </customValue>
    <customValue>
        <fullName>APAC - WA</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - France</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Germany</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - International</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Italy</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Nordics</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Poland</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - Spain</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA - UK</fullName>
    </customValue>
    <customValue>
        <fullName>LATAM</fullName>
    </customValue>
    <customValue>
        <fullName>US - Central</fullName>
    </customValue>
    <customValue>
        <fullName>US - East</fullName>
    </customValue>
    <customValue>
        <fullName>US - West</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
        <isActive>false</isActive>
        <label>EMEA</label>
    </customValue>
    <customValue>
        <fullName>EMEA - Switzerland</fullName>
        <isActive>false</isActive>
        <label>EMEA - Switzerland</label>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TDGOpportunityTriggerHandler.cls
public with sharing class TDGOpportunityTriggerHandler {
    public static final String SETTING_NAME = Test.isRunningTest() ? 'TestContext' : 'Default';
    
    public void afterInsert(List<Opportunity> newList) {
        updateRegion(newList, null);
    }

    public void afterUpdate(List<Opportunity> newList, Map<ID, Opportunity> oldMap) {
        updateRegion(newList, oldMap);
    }

    private void updateRegion(List<Opportunity> newList, Map<ID, Opportunity> oldMap) {
        if(!General_Setting__mdt.getInstance(SETTING_NAME).Enable_TDG_Opportunity_Trigger__c) return;
        List<Opportunity> oppsToProcess = new List<Opportunity>();

        for(Opportunity opp : newList) {
            if(oldMap != null) {
                Opportunity oldOpp = oldMap.get(opp.Id);

                if(opp.OwnerId == oldOpp.OwnerId) continue;
            }

            if(opp.Opportunity_Owner_Region__c != null) {
                oppsToProcess.add(new Opportunity(
                    ID = opp.Id,
                    Opportunity_Region__c = opp.Opportunity_Owner_Region__c
                ));
            }
        }

        if(oppsToProcess.size() > 0) {
            update oppsToProcess;
        }
    }
}