force-app/main/default/objects/Opportunity/fields/Agency_Name__c.field-meta.xml
<CustomField>
    <fullName>Agency_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>If the Agency Name field is entered, show the name of that Agency. Otherwise, show the error message.</description>
    <inlineHelpText>Enter the Agency Account facilitating the campaign, if applicable.  Do not include Brand direct accounts in this field</inlineHelpText>
    <label>Agency Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Advertising</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agency Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Enter in the End date of the campaign</description>
    <inlineHelpText>To edit this date, simply ensure that the product end dates are correct. This field will reflect the latest end date of the products.</inlineHelpText>
    <label>End Date (old)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Enter in day campaign starts</description>
    <inlineHelpText>To edit this date, simply ensure that the product start dates are correct.  This field will reflect the earliest start date of the products.</inlineHelpText>
    <label>Start Date (old)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Verity_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Verity_Revenue__c</fullName>
    <label>Verity Revenue</label>
    <summarizedField>OpportunityLineItem.Verity_Revenue__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Voiced_Budget__c.field-meta.xml
<CustomField>
    <fullName>Voiced_Budget__c</fullName>
    <description>Enter Voiced Budget for programmatic opportunities.</description>
    <inlineHelpText>This field contains 100% of spend before fees, data, etc. (i.e. what the client is willing to spend overall).</inlineHelpText>
    <label>Voiced Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Verity.recordType-meta.xml
<RecordType>
    <fullName>Verity</fullName>
    <active>true</active>
    <businessProcess>Verity</businessProcess>
    <label>Verity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Video.recordType-meta.xml
<RecordType>
    <fullName>Video</fullName>
    <active>true</active>
    <businessProcess>Video</businessProcess>
    <label>Video</label>
</RecordType>

force-app/main/default/objects/Trigger_Setting__c/Trigger_Setting__c.object-meta.xml
<CustomObject>
    <description>This object control type of operation in each object</description>
    <label>Trigger Setting</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Setting__c/fields/After_Delete__c.field-meta.xml
<CustomField>
    <fullName>After_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/fields/After_Insert__c.field-meta.xml
<CustomField>
    <fullName>After_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/fields/After_Update__c.field-meta.xml
<CustomField>
    <fullName>After_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LineItemScheduleTriggerHandlerTest.cls
@isTest
public class LineItemScheduleTriggerHandlerTest {
    
    @istest
    private static void testMethod1() {
        Trigger_Setting__c tsOppLineItem = new Trigger_Setting__c();
        tsOppLineItem.Object_Name__c   = 'OpportunityLineItem';
        tsOppLineItem.After_Insert__c = true;
        tsOppLineItem.After_Update__c = true;
        tsOppLineItem.After_Delete__c = true;
        tsOppLineItem.Name             = 'OpportunityLineItem';
        insert tsOppLineItem;
        
        Account testAcc = new Account(name = 'TestAcc');
        insert testAcc;
        
        Id pricebookId = Test.getStandardPricebookId();
        Id RecordTypeIdOpp = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Verity - Demand').getRecordTypeId();
        
        Product2 prd1 = new Product2 (Name='Video Solution - OLV',Verity_Revenue__c=5,Description='Test Product Entry 1',productCode = 'ABC', isActive = true,CanUseQuantitySchedule =true,CanUseRevenueSchedule=true);
        insert prd1;
        
        PricebookEntry pbe1 = new PricebookEntry (Product2ID=prd1.id,Pricebook2ID=pricebookId,UnitPrice=50, isActive=true);
        insert pbe1;
        
        Opportunity opp = new Opportunity(AccountId= testAcc.id,RecordTypeId=RecordTypeIdOpp,Agency_Name__c=testAcc.id,Start_Date__c = System.Today(),End_Date__c =System.Today()+ 100 ,name = 'Test Opp',CloseDate= System.Today()+ 3 ,Pricebook2Id = pbe1.Pricebook2Id, StageName ='Opportunity Identified' );
        insert opp;
        
        opportunity getOpp = [SELECT ID,pricebook2Id from opportunity where Id = :opp.Id];
        getOpp.Pricebook2Id = pricebookId;
        update getOpp;
        
        system.debug('oppPricebookId'+ [SELECT ID,pricebook2Id from opportunity where Id = :opp.Id].pricebook2Id);
        system.debug('Std PricebookId' + pricebookId);
        
        OpportunityLineItem opl1 = new OpportunityLineItem(OpportunityId= opp.id,
                                                           Start_Date__c =  System.Today()-20,End_Date__c =System.Today()+ 10,PriceBookEntryID=pbe1.id,Quantity=1,TotalPrice= 50,of_Budget__c=100 ) ;
		insert opl1;
        
        OpportunityLineItemSchedule oliSched = new OpportunityLineItemSchedule(
            OpportunityLineItemId = opl1.Id,
            Type = 'Both',
            Quantity = 2,
            Revenue = 200,Verity_Revenue__c = 10,Actual_Revenue_Verity__c = 100,
            ScheduleDate = Date.today()
        );
        
        insert oliSched;
        
        oliSched.Verity_Revenue__c = 90;
        oliSched.Actual_Revenue_Verity__c = 200;
        update oliSched;
        opp.Voiced_Budget__c = 200;
        update opp;

    }
    
}