force-app/main/default/objects/AAR_Split_Owner__c/AAR_Split_Owner__c.object-meta.xml
<CustomObject>
    <description>Advertiser Agency Relationship Split Owner</description>
    <label>AAR Split Owner</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>AAR Split Owner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AAR Split Owners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AAR_Split_Owner__c/fields/Advertiser_Agency_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Agency_Relationship__c</fullName>
    <label>Advertiser-Agency Relationship</label>
    <referenceTo>Advertiser_Agency_Relationship__c</referenceTo>
    <relationshipLabel>AAR Split Owners</relationshipLabel>
    <relationshipName>AAR_Split_Owners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AAR_Split_Owner__c/fields/Forecast_Q1__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Q1__c</fullName>
    <label>Forecast Q1</label>
    <summarizedField>Forecast_Entry__c.Forecast_Q11__c</summarizedField>
    <summaryFilterItems>
        <field>Forecast_Entry__c.IsActive__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Forecast_Entry__c.AAR_Split_Owner__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AAR_Split_Owner__c/fields/Forecast_Q2__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Q2__c</fullName>
    <label>Forecast Q2</label>
    <summarizedField>Forecast_Entry__c.Forecast_Q21__c</summarizedField>
    <summaryFilterItems>
        <field>Forecast_Entry__c.IsActive__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Forecast_Entry__c.AAR_Split_Owner__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AAR_Split_Owner__c/fields/Forecast_Q3__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Q3__c</fullName>
    <label>Forecast Q3</label>
    <summarizedField>Forecast_Entry__c.Forecast_Q31__c</summarizedField>
    <summaryFilterItems>
        <field>Forecast_Entry__c.IsActive__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Forecast_Entry__c.AAR_Split_Owner__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AAR_Split_Owner__c/fields/Forecast_Q4__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Q4__c</fullName>
    <label>Forecast Q4</label>
    <summarizedField>Forecast_Entry__c.Forecast_Q41__c</summarizedField>
    <summaryFilterItems>
        <field>Forecast_Entry__c.IsActive__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Forecast_Entry__c.AAR_Split_Owner__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AAR_Split_Owner__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AAR_Split_Owners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Image</fullName>
            </value>
            <value>
                <fullName>In-Screen</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Slot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Advertising.recordType-meta.xml
<RecordType>
    <fullName>Advertising</fullName>
    <active>true</active>
    <label>Advertising</label>
</RecordType>

force-app/main/default/objects/Advertiser_Agency_Relationship__c/Advertiser_Agency_Relationship__c.object-meta.xml
<CustomObject>
    <description>Advertiser Agency Relationship</description>
    <label>Advertiser-Agency Relationship</label>
    <nameField>
        <displayFormat>AAR-{000000}</displayFormat>
        <label>Advertiser Agency Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advertiser-Agency Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Entry__c/Forecast_Entry__c.object-meta.xml
<CustomObject>
    <description>Stores manually entered forecast entry</description>
    <label>Forecast Entry</label>
    <nameField>
        <displayFormat>FE-{00000}</displayFormat>
        <label>Forecast Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Entry__c/fields/AAR_Split_Owner__c.field-meta.xml
<CustomField>
    <fullName>AAR_Split_Owner__c</fullName>
    <label>AAR Split Owner</label>
    <referenceTo>AAR_Split_Owner__c</referenceTo>
    <relationshipLabel>Forecast Entries</relationshipLabel>
    <relationshipName>Forecast_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Activity_Last_30_Days__c.field-meta.xml
<CustomField>
    <fullName>Activity_Last_30_Days__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activity Last 30 Days</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Activity_Last_60_Days__c.field-meta.xml
<CustomField>
    <fullName>Activity_Last_60_Days__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activity Last 60 Days</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Forecast_Q1__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Q1__c</fullName>
    <label>Q1 CY Booking</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Forecast_Q2__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Q2__c</fullName>
    <label>Q2 CY Booking</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Forecast_Q3__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Q3__c</fullName>
    <label>Q3 CY Booking</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Forecast_Q4__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Q4__c</fullName>
    <label>Q4 CY Booking</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active Forecast Entry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Pipeline_Q1__c.field-meta.xml
<CustomField>
    <fullName>Pipeline_Q1__c</fullName>
    <label>Q1 CY Pipeline</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Pipeline_Q2__c.field-meta.xml
<CustomField>
    <fullName>Pipeline_Q2__c</fullName>
    <label>Q2 CY Pipeline</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Pipeline_Q3__c.field-meta.xml
<CustomField>
    <fullName>Pipeline_Q3__c</fullName>
    <label>Q3 CY Pipeline</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Pipeline_Q4__c.field-meta.xml
<CustomField>
    <fullName>Pipeline_Q4__c</fullName>
    <label>Q4 CY Pipeline</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Core Media</fullName>
                <default>true</default>
                <label>Core Media</label>
            </value>
            <value>
                <fullName>CTV</fullName>
            </value>
            <value>
                <fullName>OLV</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Q1_NY_Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Q1_NY_Pipeline__c</fullName>
    <label>Q1 NY Pipeline</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Q1_PY_Bookings__c.field-meta.xml
<CustomField>
    <fullName>Q1_PY_Bookings__c</fullName>
    <label>Q1 PY Bookings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Q2_NY_Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Q2_NY_Pipeline__c</fullName>
    <label>Q2 NY Pipeline</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Q2_PY_Bookings__c.field-meta.xml
<CustomField>
    <fullName>Q2_PY_Bookings__c</fullName>
    <label>Q2 PY Bookings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Q3_NY_Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Q3_NY_Pipeline__c</fullName>
    <label>Q3 NY Pipeline</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Q3_PY_Bookings__c.field-meta.xml
<CustomField>
    <fullName>Q3_PY_Bookings__c</fullName>
    <label>Q3 PY Bookings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Q4_NY_Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Q4_NY_Pipeline__c</fullName>
    <label>Q4 NY Pipeline</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Q4_PY_Bookings__c.field-meta.xml
<CustomField>
    <fullName>Q4_PY_Bookings__c</fullName>
    <label>Q4 PY Bookings</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agency_Name__c.field-meta.xml
<CustomField>
    <fullName>Agency_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>If the Agency Name field is entered, show the name of that Agency. Otherwise, show the error message.</description>
    <inlineHelpText>Enter the Agency Account facilitating the campaign, if applicable.  Do not include Brand direct accounts in this field</inlineHelpText>
    <label>Agency Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Advertising</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agency Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Activation.recordType-meta.xml
<RecordType>
    <fullName>Activation</fullName>
    <active>true</active>
    <businessProcess>Advertising</businessProcess>
    <label>Activation</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Advertising.recordType-meta.xml
<RecordType>
    <fullName>Advertising</fullName>
    <active>true</active>
    <businessProcess>Advertising</businessProcess>
    <label>Advertising</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Verity.recordType-meta.xml
<RecordType>
    <fullName>Verity</fullName>
    <active>true</active>
    <businessProcess>Verity</businessProcess>
    <label>Verity</label>
</RecordType>

force-app/main/default/classes/ForecastEntryCalcBatch.cls
public class ForecastEntryCalcBatch implements Database.Batchable<SObject>, Schedulable {

    public static final Id ActivationRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Activation').getRecordTypeId();
    public static final Id AdvertisingRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Advertising').getRecordTypeId();
    public static final Id VerityDemandRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Verity - Demand').getRecordTypeId();

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT Id,Product__c,currencyISOCode,AAR_Split_Owner__r.Advertiser_Agency_Relationship__r.Agency__c,AAR_Split_Owner__r.Advertiser_Agency_Relationship__r.Advertiser__c, AAR_Split_Owner__r.Owner__c, Name, Forecast_Q1__c, Forecast_Q2__c, Forecast_Q3__c, Forecast_Q4__c, Pipeline_Q1__c, Pipeline_Q2__c, Pipeline_Q3__c, Pipeline_Q4__c, Q1_PY_Bookings__c, Q2_PY_Bookings__c, Q3_PY_Bookings__c, Q4_PY_Bookings__c, Q1_NY_Pipeline__c, Q2_NY_Pipeline__c, Q3_NY_Pipeline__c, Q4_NY_Pipeline__c FROM Forecast_Entry__c WHERE  IsActive__c = true');
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        List<Forecast_Entry__c> forecastEntries = (List<Forecast_Entry__c>) scope;
        processForecastEntries(forecastEntries);

    }

    public void finish(Database.BatchableContext bc) {
    }

    public void execute(SchedulableContext sc) {
        Database.executeBatch(new ForecastEntryCalcBatch(), 200);
    }

    public static void processForecastEntries(List<forecast_entry__c> forecastEntries) {

        Set<Id> entryIds = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();
        Set<Id> allAccountIds = new Set<Id>();
        Set<Id> AdvertiserIds = new Set<Id>();

        for(Forecast_Entry__c FE : forecastEntries){
            allAccountIds.add(FE.AAR_Split_Owner__r.Advertiser_Agency_Relationship__r.Agency__c);
            allAccountIds.add(FE.AAR_Split_Owner__r.Advertiser_Agency_Relationship__r.Advertiser__c);
            
            if(FE.Product__c == 'Core Media'){
                accountIds.add(FE.AAR_Split_Owner__r.Advertiser_Agency_Relationship__r.Agency__c);
                accountIds.add(FE.AAR_Split_Owner__r.Advertiser_Agency_Relationship__r.Advertiser__c);
                AdvertiserIds.add(FE.AAR_Split_Owner__r.Advertiser_Agency_Relationship__r.Advertiser__c);
            }
        }


        List<OpportunitySplit> OpportunitySplitList = [select id,SplitPercentage,OpportunityId,SplitOwnerId from OpportunitySplit 
                                                        where Opportunity.AccountId IN :AdvertiserIds
                                                        AND (Opportunity.RecordTypeId = :ActivationRecordTypeId
                                                            OR Opportunity.RecordTypeId = :AdvertisingRecordTypeId
                                                            OR Opportunity.RecordTypeId = :VerityDemandRecordTypeId)
                                                        AND Opportunity.StageName != 'Closed/Lost'
                                                        AND Opportunity.StageName != 'Discard'
                                                        ];
        Map<Id,Map<Id,Decimal>> OpptySplitPercentage = new Map<Id,Map<Id,Decimal>>();

        for(OpportunitySplit OS : OpportunitySplitList){
            if(OpptySplitPercentage.containsKey(OS.OpportunityId)){
                OpptySplitPercentage.get(OS.OpportunityId).put(OS.splitOwnerId,OS.SplitPercentage);
            }else{
                Map<Id,Decimal> splitOwnerToPercentage = new Map<Id,Decimal>();
                splitOwnerToPercentage.put(OS.splitOwnerId,OS.SplitPercentage);
                OpptySplitPercentage.put(OS.OpportunityId,splitOwnerToPercentage);
            }
        }

        Map<Id, Date> accountActivityDateMap  = getRecentActivityDate(allAccountIds);

        List<OpportunityLineItemSchedule> schedules = [
            SELECT Id, ScheduleDate,CurrencyIsoCode,  Revenue, OpportunityLineItem.OpportunityId,OpportunityLineItem.Opportunity.Agency_Name__c,OpportunityLineItem.Opportunity.AccountId,OpportunityLineItem.Opportunity.CurrencyISOCode,OpportunityLineItem.Opportunity.CloseDate,
                OpportunityLineItem.Opportunity.StageName,OpportunityLineItem.Opportunity.isClosed, OpportunityLineItem.Opportunity.OwnerId
            FROM OpportunityLineItemSchedule
            WHERE (OpportunityLineItem.Opportunity.AccountId IN :AdvertiserIds) 
            AND (OpportunityLineItem.Opportunity.RecordTypeId = :ActivationRecordTypeId
                OR OpportunityLineItem.Opportunity.RecordTypeId = :AdvertisingRecordTypeId
                OR OpportunityLineItem.Opportunity.RecordTypeId = :VerityDemandRecordTypeId)
            AND OpportunityLineItem.Opportunity.StageName != 'Closed/Lost'
            AND OpportunityLineItem.Opportunity.StageName != 'Discard'
            AND (ScheduleDate = THIS_YEAR OR ScheduleDate = NEXT_YEAR OR ScheduleDate = LAST_YEAR)
        ];

        Map<String,List<OpportunityLineItemSchedule>> advertiserAgencyIdToOLISchedulesMap = new Map<String,List<OpportunityLineItemSchedule>>();

        for(OpportunityLineItemSchedule sch : schedules){
            if(advertiserAgencyIdToOLISchedulesMap.get(sch.OpportunityLineItem.Opportunity.AccountId+'-'+sch.OpportunityLineItem.Opportunity.Agency_Name__c)==null){
                List<OpportunityLineItemSchedule> oliScheduleList = new List<OpportunityLineItemSchedule>();
                oliScheduleList.add(sch);
                advertiserAgencyIdToOLISchedulesMap.put(sch.OpportunityLineItem.Opportunity.AccountId+'-'+sch.OpportunityLineItem.Opportunity.Agency_Name__c,oliScheduleList);
            }else{
                advertiserAgencyIdToOLISchedulesMap.get(sch.OpportunityLineItem.Opportunity.AccountId+'-'+sch.OpportunityLineItem.Opportunity.Agency_Name__c).add(sch);
            }
        }

        Integer currentYear = Date.today().year();
        Date today = System.today();

        for (forecast_entry__c entry : forecastEntries) {
            
            entry.Activity_Last_30_Days__c = false;
            entry.Activity_Last_60_Days__c = false;

            if(accountActivityDateMap.get(entry.AAR_Split_Owner__r.Advertiser_Agency_Relationship__r.Agency__c) != null){
                
                Date lastActivityDate = accountActivityDateMap.get(entry.AAR_Split_Owner__r.Advertiser_Agency_Relationship__r.Agency__c);

                // Check the date range and set the checkboxes accordingly
                if (lastActivityDate <= today && lastActivityDate >= today.addDays(-30)) {
                    entry.Activity_Last_30_Days__c = true;
                }

                if (lastActivityDate <=  today && lastActivityDate >= today.addDays(-60)) {
                    entry.Activity_Last_60_Days__c = true;
                }
            }

            if(accountActivityDateMap.get(entry.AAR_Split_Owner__r.Advertiser_Agency_Relationship__r.Advertiser__c) != null){
                
                Date lastActivityDate = accountActivityDateMap.get(entry.AAR_Split_Owner__r.Advertiser_Agency_Relationship__r.Advertiser__c);

                // Check the date range and set the checkboxes accordingly
                if (lastActivityDate <= today && lastActivityDate >= today.addDays(-30)) {
                    entry.Activity_Last_30_Days__c = true;
                }

                if (lastActivityDate <=  today && lastActivityDate >= today.addDays(-60)) {
                    entry.Activity_Last_60_Days__c = true;
                }
            }
            
            if(entry.Product__c == 'Core Media'){
                //CY Bookings
                entry.Forecast_Q1__c = 0;
                entry.Forecast_Q2__c = 0;
                entry.Forecast_Q3__c = 0;
                entry.Forecast_Q4__c = 0;

                //CY Pipeline
                entry.Pipeline_Q1__c = 0;
                entry.Pipeline_Q2__c = 0;
                entry.Pipeline_Q3__c = 0;
                entry.Pipeline_Q4__c = 0;

                //PY Bookings
                entry.Q1_PY_Bookings__c = 0;
                entry.Q2_PY_Bookings__c = 0;
                entry.Q3_PY_Bookings__c = 0;
                entry.Q4_PY_Bookings__c = 0;

                //NY Pipeline
                entry.Q1_NY_Pipeline__c = 0;
                entry.Q2_NY_Pipeline__c = 0;
                entry.Q3_NY_Pipeline__c = 0;
                entry.Q4_NY_Pipeline__c = 0;
                
                if(advertiserAgencyIdToOLISchedulesMap.get(entry.AAR_Split_Owner__r.Advertiser_Agency_Relationship__r.Advertiser__c+'-'+entry.AAR_Split_Owner__r.Advertiser_Agency_Relationship__r.Agency__c) != null){
                    for (OpportunityLineItemSchedule schedule : advertiserAgencyIdToOLISchedulesMap.get(entry.AAR_Split_Owner__r.Advertiser_Agency_Relationship__r.Advertiser__c+'-'+entry.AAR_Split_Owner__r.Advertiser_Agency_Relationship__r.Agency__c)) {

                        if(OpptySplitPercentage.get(schedule.OpportunityLineItem.OpportunityId).get(schedule.OpportunityLineItem.Opportunity.OwnerId)==null){
                            continue;
                        }

                        Integer scheduleYear = schedule.ScheduleDate.year();
                        Integer quarter = checkScheduleDateQuarters(schedule.ScheduleDate);

                        Decimal revenue = schedule.Revenue;
                        if(revenue > 0){
                            revenue = revenue * (CurrencyConversionUtility.getExchangeRate(entry.CurrencyISOCode,schedule.ScheduleDate)/ CurrencyConversionUtility.getExchangeRate(schedule.CurrencyISOCode,schedule.ScheduleDate));
                        }

                        if(OpptySplitPercentage.get(schedule.OpportunityLineItem.OpportunityId)!=null){
                            revenue =  revenue * (OpptySplitPercentage.get(schedule.OpportunityLineItem.OpportunityId).get(schedule.OpportunityLineItem.Opportunity.OwnerId)/100);
                        }

                        if (quarter > 0) {
                            if (scheduleYear == currentYear) {
                                // Current Year logic
                                if (schedule.OpportunityLineItem.Opportunity.StageName == 'Closed/Won') {
                                    if (quarter == 1) entry.Forecast_Q1__c += revenue;
                                    else if (quarter == 2) entry.Forecast_Q2__c += revenue;
                                    else if (quarter == 3) entry.Forecast_Q3__c += revenue;
                                    else if (quarter == 4) entry.Forecast_Q4__c += revenue;
                                } else if (!schedule.OpportunityLineItem.Opportunity.isClosed) {
                                    if (quarter == 1) entry.Pipeline_Q1__c += revenue;
                                    else if (quarter == 2) entry.Pipeline_Q2__c += revenue;
                                    else if (quarter == 3) entry.Pipeline_Q3__c += revenue;
                                    else if (quarter == 4) entry.Pipeline_Q4__c += revenue;
                                }
                            } else if (scheduleYear == currentYear - 1 && schedule.OpportunityLineItem.Opportunity.StageName == 'Closed/Won') {
                                if (quarter == 1) entry.Q1_PY_Bookings__c += revenue;
                                else if (quarter == 2) entry.Q2_PY_Bookings__c += revenue;
                                else if (quarter == 3) entry.Q3_PY_Bookings__c += revenue;
                                else if (quarter == 4) entry.Q4_PY_Bookings__c += revenue;
                            } else if (scheduleYear == currentYear + 1 && !schedule.OpportunityLineItem.Opportunity.isClosed) {
                                if (quarter == 1) entry.Q1_NY_Pipeline__c += revenue;
                                else if (quarter == 2) entry.Q2_NY_Pipeline__c += revenue;
                                else if (quarter == 3) entry.Q3_NY_Pipeline__c += revenue;
                                else if (quarter == 4) entry.Q4_NY_Pipeline__c += revenue;
                            }
                        }
                
                    }
                }
            }
            
        }

        update forecastEntries;
    
    }

    public static Integer checkScheduleDateQuarters(Date scheduleDate) {
        Integer month = scheduleDate.month();
        if (month <= 3) return 1;   
        if (month <= 6) return 2;   
        if (month <= 9) return 3;   
        return 4;                   
    }


    public static Map<Id, Date> getRecentActivityDate(Set<Id> advertiserAgencyIds) {
        // Initialize a map to track the last activity dates
        Map<Id, Date> accountActivityMap = new Map<Id, Date>();

        List<Account> accList = [SELECT Id, 
                                (SELECT id,ActivityDate,ActivityType from ActivityHistories WHERE ActivityDate = LAST_N_DAYS:60 ORDER BY ActivityDate DESC LIMIT 1),
                                (SELECT Id,ActivityDate FROM OpenActivities WHERE ActivityDate = LAST_N_DAYS:60 ORDER BY ActivityDate DESC LIMIT 1)
                                FROM Account WHERE Id IN :advertiserAgencyIds];

        for(Account acc : accList){

            if(acc.activityhistories != null && !acc.activityhistories.isEmpty()){
                accountActivityMap.put(acc.Id,acc.activityhistories[0].ActivityDate);
            }

            if(acc.OpenActivities != null && !acc.OpenActivities.isEmpty()){
                if(accountActivityMap.get(acc.Id) == null || (accountActivityMap.get(acc.Id) != null && (accountActivityMap.get(acc.Id) < acc.OpenActivities[0].ActivityDate))){
                    accountActivityMap.put(acc.Id,acc.OpenActivities[0].ActivityDate);
                }
            }
        }

        return accountActivityMap;
    }
}