force-app/main/default/objects/AAR_Split_Owner__c/AAR_Split_Owner__c.object-meta.xml
<CustomObject>
    <description>Advertiser Agency Relationship Split Owner</description>
    <label>AAR Split Owner</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>AAR Split Owner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AAR Split Owners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AAR_Split_Owner__c/fields/Account_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Account_Forecast__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Forecast</label>
    <referenceTo>Account_Forecast__c</referenceTo>
    <relationshipLabel>AAR Split Owners</relationshipLabel>
    <relationshipName>AAR_Split_Owners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AAR_Split_Owner__c/fields/Advertiser_Agency_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Agency_Relationship__c</fullName>
    <label>Advertiser-Agency Relationship</label>
    <referenceTo>Advertiser_Agency_Relationship__c</referenceTo>
    <relationshipLabel>AAR Split Owners</relationshipLabel>
    <relationshipName>AAR_Split_Owners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AAR_Split_Owner__c/fields/Forecast_Q1__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Q1__c</fullName>
    <label>Forecast Q1</label>
    <summarizedField>Forecast_Entry__c.Forecast_Q11__c</summarizedField>
    <summaryFilterItems>
        <field>Forecast_Entry__c.IsActive__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Forecast_Entry__c.AAR_Split_Owner__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AAR_Split_Owner__c/fields/Forecast_Q2__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Q2__c</fullName>
    <label>Forecast Q2</label>
    <summarizedField>Forecast_Entry__c.Forecast_Q21__c</summarizedField>
    <summaryFilterItems>
        <field>Forecast_Entry__c.IsActive__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Forecast_Entry__c.AAR_Split_Owner__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Image</fullName>
            </value>
            <value>
                <fullName>In-Screen</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Slot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Forecast__c/Account_Forecast__c.object-meta.xml
<CustomObject>
    <description>Forecast details calculated by AccountForecastBatch</description>
    <label>Account Forecast</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Account Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Forecast__c/fields/Advertiser_Agency_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Agency_Relationship__c</fullName>
    <label>Advertiser-Agency Relationship</label>
    <referenceTo>Advertiser_Agency_Relationship__c</referenceTo>
    <relationshipLabel>Account Forecasts</relationshipLabel>
    <relationshipName>Account_Forecasts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Forecast__c/fields/Bookings_Current_Year__c.field-meta.xml
<CustomField>
    <fullName>Bookings_Current_Year__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Bookings (Current Year)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Forecast__c/fields/Pipeline_Current_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Pipeline_Current_Quarter__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Pipeline (Current Quarter)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Advertiser_Agency_Relationship__c/Advertiser_Agency_Relationship__c.object-meta.xml
<CustomObject>
    <description>Advertiser Agency Relationship</description>
    <label>Advertiser-Agency Relationship</label>
    <nameField>
        <displayFormat>AAR-{000000}</displayFormat>
        <label>Advertiser Agency Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advertiser-Agency Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Advertiser_Agency_Relationship__c/fields/Advertiser__c.field-meta.xml
<CustomField>
    <fullName>Advertiser__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Advertiser</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advertiser-Agency Relationships</relationshipLabel>
    <relationshipName>Advertiser_Agency_Relationships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advertiser_Agency_Relationship__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advertiser-Agency Relationships (Agency)</relationshipLabel>
    <relationshipName>Advertiser_Agency_Relationships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Advertiser_Agency_Relationship__c/fields/Bookings_Current_Year__c.field-meta.xml
<CustomField>
    <fullName>Bookings_Current_Year__c</fullName>
    <label>Bookings (Current Year)</label>
    <summarizedField>Account_Forecast__c.Bookings_Current_Year__c</summarizedField>
    <summaryForeignKey>Account_Forecast__c.Advertiser_Agency_Relationship__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Advertiser_Agency_Relationship__c/fields/Forecast_Q1__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Q1__c</fullName>
    <label>Forecast Q1</label>
    <summarizedField>AAR_Split_Owner__c.Forecast_Q1__c</summarizedField>
    <summaryFilterItems>
        <field>AAR_Split_Owner__c.Is_Active__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>AAR_Split_Owner__c.Advertiser_Agency_Relationship__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Advertiser_Agency_Relationship__c/fields/Forecast_Q2__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Q2__c</fullName>
    <label>Forecast Q2</label>
    <summarizedField>AAR_Split_Owner__c.Forecast_Q2__c</summarizedField>
    <summaryFilterItems>
        <field>AAR_Split_Owner__c.Is_Active__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>AAR_Split_Owner__c.Advertiser_Agency_Relationship__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Advertiser_Agency_Relationship__c/fields/Pipeline_Current_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Pipeline_Current_Quarter__c</fullName>
    <label>Pipeline (Current Quarter)</label>
    <summarizedField>Account_Forecast__c.Pipeline_Current_Quarter__c</summarizedField>
    <summaryForeignKey>Account_Forecast__c.Advertiser_Agency_Relationship__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/Forecast_Entry__c.object-meta.xml
<CustomObject>
    <description>Stores manually entered forecast entry</description>
    <label>Forecast Entry</label>
    <nameField>
        <displayFormat>FE-{00000}</displayFormat>
        <label>Forecast Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecast Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Entry__c/fields/AAR_Split_Owner__c.field-meta.xml
<CustomField>
    <fullName>AAR_Split_Owner__c</fullName>
    <label>AAR Split Owner</label>
    <referenceTo>AAR_Split_Owner__c</referenceTo>
    <relationshipLabel>Forecast Entries</relationshipLabel>
    <relationshipName>Forecast_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Forecast_Q1__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Q1__c</fullName>
    <label>Q1 CY Booking</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Forecast_Q2__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Q2__c</fullName>
    <label>Q2 CY Booking</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active Forecast Entry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Forecast_Entry__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Core Media</fullName>
                <default>true</default>
                <label>Core Media</label>
            </value>
            <value>
                <fullName>CTV</fullName>
            </value>
            <value>
                <fullName>OLV</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agency_Name__c.field-meta.xml
<CustomField>
    <fullName>Agency_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>If the Agency Name field is entered, show the name of that Agency. Otherwise, show the error message.</description>
    <inlineHelpText>Enter the Agency Account facilitating the campaign, if applicable.  Do not include Brand direct accounts in this field</inlineHelpText>
    <label>Agency Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Advertising</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agency Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Enter in the End date of the campaign</description>
    <inlineHelpText>To edit this date, simply ensure that the product end dates are correct. This field will reflect the latest end date of the products.</inlineHelpText>
    <label>End Date (old)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Enter in day campaign starts</description>
    <inlineHelpText>To edit this date, simply ensure that the product start dates are correct.  This field will reflect the earliest start date of the products.</inlineHelpText>
    <label>Start Date (old)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Verity_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Verity_Revenue__c</fullName>
    <label>Verity Revenue</label>
    <summarizedField>OpportunityLineItem.Verity_Revenue__c</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Activation.recordType-meta.xml
<RecordType>
    <fullName>Activation</fullName>
    <active>true</active>
    <businessProcess>Advertising</businessProcess>
    <label>Activation</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Video.recordType-meta.xml
<RecordType>
    <fullName>Video</fullName>
    <active>true</active>
    <businessProcess>Video</businessProcess>
    <label>Video</label>
</RecordType>

force-app/main/default/objects/Trigger_Setting__c/Trigger_Setting__c.object-meta.xml
<CustomObject>
    <description>This object control type of operation in each object</description>
    <label>Trigger Setting</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Setting__c/fields/After_Delete__c.field-meta.xml
<CustomField>
    <fullName>After_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/fields/After_Insert__c.field-meta.xml
<CustomField>
    <fullName>After_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/fields/After_Update__c.field-meta.xml
<CustomField>
    <fullName>After_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/fields/Before_Delete__c.field-meta.xml
<CustomField>
    <fullName>Before_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/fields/Prevent_Recursion__c.field-meta.xml
<CustomField>
    <fullName>Prevent_Recursion__c</fullName>
    <label>Prevent Recursion</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ForecastEntryCalcBatchTest.cls
@isTest
public class ForecastEntryCalcBatchTest {
	
	private static void setupTestData() {
        
        List<Trigger_Setting__c> TSList = new List<Trigger_Setting__c>();
        
        Trigger_Setting__c tsOppLineItem = new Trigger_Setting__c();
        tsOppLineItem.Object_Name__c   = 'OpportunityLineItem';
        tsOppLineItem.After_Insert__c = true;
        tsOppLineItem.After_Update__c = true;
        tsOppLineItem.After_Delete__c = true;
        tsOppLineItem.Name             = 'OpportunityLineItem';
        TSList.add(tsOppLineItem);
        
        // Insert Trigger Settings for OpportunityContactRole
        Trigger_Setting__c tsOppConRole = new Trigger_Setting__c();
        tsOppConRole.Object_Name__c   = 'OpportunityContactRole';
        tsOppConRole.After_Insert__c = false;
        tsOppConRole.After_Update__c = false;
        tsOppConRole.Before_Delete__c = false;
        tsOppConRole.Prevent_Recursion__c = 'isPrimary';
        tsOppConRole.Name             = 'Opportunity Contact Role';
        TSList.add(tsOppConRole);
        
        insert TSList;

        Account testAccount = new Account(Name = 'Test Advertiser');
        insert testAccount;

        // Create a task with a due date in the past
        Task pastTask = new Task(
            Subject = 'Follow Up',
            WhatId = testAccount.Id,
            ActivityDate = Date.today().addDays(-10), // 10 days in the past
            Status = 'Not Started',
            Priority = 'Normal'
        );
        insert pastTask;
        
        // Create an event with a start date and end date in the past
        Event pastEvent = new Event(
            Subject = 'Past Meeting',
            WhatId = testAccount.Id,
            StartDateTime = DateTime.now().addDays(-7).addHours(-2), // 7 days and 2 hours in the past
            EndDateTime = DateTime.now().addDays(-7).addHours(-1),   // 7 days and 1 hour in the past
            DurationInMinutes = 60,
            Location = 'Conference Room',
            Description = 'Test meeting for past event',
            IsAllDayEvent = false
        );
        insert pastEvent;
        
        Account agencyAccount = new Account(Name = 'Test Agency');
        insert agencyAccount;

        // Create a task with a due date in the past
        Task pastTask1 = new Task(
            Subject = 'Follow Up',
            WhatId = agencyAccount.Id,
            ActivityDate = Date.today().addDays(-10), // 10 days in the past
            Status = 'Not Started',
            Priority = 'Normal'
        );
        insert pastTask1;
        
        // Create an event with a start date and end date in the past
        Event pastEvent1 = new Event(
            Subject = 'Past Meeting',
            WhatId = agencyAccount.Id,
            StartDateTime = DateTime.now().addDays(-7).addHours(-2), // 7 days and 2 hours in the past
            EndDateTime = DateTime.now().addDays(-7).addHours(-1),   // 7 days and 1 hour in the past
            DurationInMinutes = 60,
            Location = 'Conference Room',
            Description = 'Test meeting for past event',
            IsAllDayEvent = false
        );
        insert pastEvent1;
        
        Advertiser_Agency_Relationship__c aar = new Advertiser_Agency_Relationship__c(
            Advertiser__c = testAccount.Id
            //Agency__c = agencyAccount.Id
        );
        insert aar;

        Account_Forecast__c forecast = new Account_Forecast__c(
            Advertiser_Agency_Relationship__c = aar.Id,
            Bookings_Current_Year__c = 10000,
            Pipeline_Current_Quarter__c = 5000
        );
        insert forecast;

        AAR_Split_Owner__c splitOwner = new AAR_Split_Owner__c(
            Advertiser_Agency_Relationship__c = aar.Id,
            Is_Active__c = true
        );
        insert splitOwner;

       

        // Create Advertiser-Agency Relationship
        Advertiser_Agency_Relationship__c aar2 = new Advertiser_Agency_Relationship__c(
            Advertiser__c = testAccount.Id,
            Agency__c = agencyAccount.Id
        );
        insert aar2;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        Product2 prd1 = new Product2 (Name='Video Solution - OLV',Description='Test Product Entry 1',productCode = 'ABC', isActive = true,CanUseQuantitySchedule =true,CanUseRevenueSchedule=true);
        insert prd1;
        
        PricebookEntry pbe1 = new PricebookEntry (Product2ID=prd1.id,Pricebook2ID=pricebookId,UnitPrice=50, isActive=true);
        insert pbe1;
        
        Id ActivationRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Activation').getRecordTypeId();

        Opportunity opp = new Opportunity(AccountId= testAccount.id,RecordTypeId = ActivationRecordTypeId,/*Agency_Name__c=testAccount.id,*/Start_Date__c = System.Today(),End_Date__c =System.Today()+ 100 ,name = 'Test Opp',CloseDate= System.Today()+ 3 ,Pricebook2Id = pbe1.Pricebook2Id, StageName ='Opportunity Identified' );
        insert opp;
        
        opportunity getOpp = [SELECT ID,pricebook2Id,stageName from opportunity where Id = :opp.Id];
        getOpp.Pricebook2Id = pricebookId;
        getOpp.StageName = 'Closed/Won';
        
        update getOpp;
        

        // Query an existing OpportunitySplitType
        /*OpportunitySplitType splitType = [SELECT Id, IsActive FROM OpportunitySplitType WHERE IsActive = TRUE AND DeveloperName = 'Overlay' LIMIT 1];

        // Create an OpportunitySplit record
        OpportunitySplit oppSplit = new OpportunitySplit(
            OpportunityId = opp.Id,
            SplitTypeId = splitType.Id,
            SplitPercentage = 100,
            SplitOwnerId = UserInfo.getUserId()
        );
        insert oppSplit;*/

        system.debug('##### '+[select id,SplitPercentage,OpportunityId,SplitOwnerId,Opportunity.recordtype.Name,opportunity.stageName,Opportunity.AccountId from OpportunitySplit]);

        OpportunityLineItem opl1 = new OpportunityLineItem(OpportunityId= opp.id,Start_Date__c =  System.Today()-20,End_Date__c =System.Today()+ 10,PriceBookEntryID=pbe1.id,Quantity=1,TotalPrice= 50 ) ;
		insert opl1;
        
        OpportunityLineItemSchedule oliSched = new OpportunityLineItemSchedule(
            OpportunityLineItemId = opl1.Id,
            Type = 'Both',
            Quantity = 2,
            Revenue = 200,Verity_Revenue__c = 10,
            ScheduleDate = Date.today()
        );
        
        insert oliSched;
        
        OpportunityLineItemSchedule oliSched1 = new OpportunityLineItemSchedule(
            OpportunityLineItemId = opl1.Id,
            Type = 'Both',
            Quantity = 2,
            Revenue = 200,Verity_Revenue__c = 10,
            ScheduleDate = Date.today().addYears(-1)
        );
        
        insert oliSched1;
        
        OpportunityLineItemSchedule oliSched2 = new OpportunityLineItemSchedule(
            OpportunityLineItemId = opl1.Id,
            Type = 'Both',
            Quantity = 2,
            Revenue = 200,Verity_Revenue__c = 10,
            ScheduleDate = Date.today().addYears(+1)
        );
        
        insert oliSched2;
         
         Forecast_Entry__c forecastEntry = new Forecast_Entry__c(
            Product__c = 'Core Media',
            Forecast_Q1__c = 1000,
            Forecast_Q2__c = 2000,
            AAR_Split_Owner__c = splitOwner.Id,
            IsActive__c = true
        );
        insert forecastEntry;
    }

	@IsTest
    static void testforecastEntries() {
        setupTestData();

        Test.startTest();

        Database.executeBatch(new ForecastEntryCalcBatch(), 200);
        Test.stopTest();

    }

}