force-app/main/default/objects/Account_Campaign_Junction__c/Account_Campaign_Junction__c.object-meta.xml
<CustomObject>
    <label>Account Campaign Junction</label>
    <nameField>
        <displayFormat>ACJ-{0000000}</displayFormat>
        <label>Account to Campaign Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Campaign Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign/fields/Approved_by_Management__c.field-meta.xml
<CustomField>
    <fullName>Approved_by_Management__c</fullName>
    <label>Approved by Management</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Cost_Breakdown__c.field-meta.xml
<CustomField>
    <fullName>Cost_Breakdown__c</fullName>
    <label>Cost Breakdown</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Event_Registration_Method__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration_Method__c</fullName>
    <label>Event Registration Method</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Splash Page</fullName>
            </value>
            <value>
                <fullName>Email Invitation</fullName>
            </value>
            <value>
                <fullName>Ceros Interactive Page</fullName>
            </value>
            <value>
                <fullName>Sponsored</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <label>Campaign</label>
</RecordType>

force-app/main/default/objects/Client_Team__c/Client_Team__c.object-meta.xml
<CustomObject>
    <label>Client Team</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Client Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Team__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <label>Agent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Team</relationshipLabel>
    <relationshipName>Client_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_Team__c/fields/Client_Account__c.field-meta.xml
<CustomField>
    <fullName>Client_Account__c</fullName>
    <label>Client Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Team</relationshipLabel>
    <relationshipName>Client_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Client_Team__c.field-meta.xml
<CustomField>
    <fullName>Client_Team__c</fullName>
    <label>Client Team</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <label>Persona</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Agency VIP</fullName>
            </value>
            <value>
                <fullName>Banker</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>DSP or Trading Desk</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Influencer</fullName>
            </value>
            <value>
                <fullName>Investor</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Publisher</fullName>
            </value>
            <value>
                <fullName>Reporter / Analyst</fullName>
            </value>
            <value>
                <fullName>Rights Holder</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Student / Job Seeker</fullName>
            </value>
            <value>
                <fullName>Technology Partner</fullName>
            </value>
            <value>
                <fullName>VC and Angel</fullName>
            </value>
            <value>
                <fullName>SSP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/Trigger_Setting__c.object-meta.xml
<CustomObject>
    <description>This object control type of operation in each object</description>
    <label>Trigger Setting</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Setting__c/fields/After_Delete__c.field-meta.xml
<CustomField>
    <fullName>After_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/fields/After_Insert__c.field-meta.xml
<CustomField>
    <fullName>After_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/fields/After_Undelete__c.field-meta.xml
<CustomField>
    <fullName>After_Undelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Undelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/fields/After_Update__c.field-meta.xml
<CustomField>
    <fullName>After_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/fields/Before_Delete__c.field-meta.xml
<CustomField>
    <fullName>Before_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/fields/Before_Insert__c.field-meta.xml
<CustomField>
    <fullName>Before_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/fields/Before_Update__c.field-meta.xml
<CustomField>
    <fullName>Before_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__c/fields/Prevent_Recursion__c.field-meta.xml
<CustomField>
    <fullName>Prevent_Recursion__c</fullName>
    <label>Prevent Recursion</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/test_TrgCampaignMember.cls
@isTest
public class test_TrgCampaignMember {
    @isTest
    public static void testCampaignMemberTrigger(){
        // Insert Trigger Settings
        Trigger_Setting__c ts = new Trigger_Setting__c();
        ts.Object_Name__c   = 'CampaignMember';
        ts.After_Insert__c = true;	
        ts.Before_Insert__c = true;
        ts.After_Undelete__c = true;
        ts.Before_Update__c = true;
        ts.After_Delete__c  = true;
        ts.Before_Delete__c = true;
        ts.After_Update__c  = true;
        ts.Name             = 'Campaign Member';
        ts.Prevent_Recursion__c = 'HasResponded';
        insert ts;
        list<account> acctList=new list<account>();
        acctList.add(new account(name='Test 005',
                                 phone='22322342342',
                                 BillingCity='Test',
                                 BillingCountry='United States',
                                 BillingPostalCode='Test',
                                 BillingState='New York',
                                 BillingStreet='Test'));
        acctList.add(new account(name='Test 004'));
        system.debug('acctList: '+ acctList);
        insert acctList;
        List<contact> contactList=new list<contact>();
        contactList.add(new contact(LastName='Test Contact',Persona__c='General',email='aa@aa.com',accountid=acctList[0].id));
        contactList.add(new contact(LastName='Test Contact2',Persona__c='General',email='aa@aa.com',accountid=acctList[1].id));
        insert contactList;
        system.debug('contactList: '+ contactList);
        
        list<client_team__c> ct= new list<client_team__c>();
        ct.add(new client_team__c(agent__c=contactList[0].id,Client_Account__c=acctList[0].id));
        ct.add(new client_team__c(agent__c=contactList[1].id,Client_Account__c=acctList[1].id));
        insert ct;
        
        Campaign c=new campaign(name='Test Campaign',
                               //type='Internal Event',
                               recordtypeid='0120P0000001uCUQAY',
                               StartDate=System.today(),
                               endDate=System.today()+7,
                               BudgetedCost=1000,
                               Cost_Breakdown__c='ashdashdg',
                               Approved_by_Management__c='Yes',
                               Event_Registration_Method__c='Sponsored');
        insert c;
		CampaignMemberStatus cms1 = new CampaignMemberStatus(CampaignId=c.Id, HasResponded=true, Label='Attended', SortOrder=6);
        CampaignMemberStatus cms2 = new CampaignMemberStatus(CampaignId=c.Id, HasResponded=True, Label='Registered', SortOrder=13); 
        //CampaignMemberStatus cms3 = new CampaignMemberStatus(CampaignId=c.Id, HasResponded=True, Label='Attended', SortOrder=4);        
        insert cms1;
        insert cms2;
        
        list<CampaignMember>  cm=new list<CampaignMember>();
        cm.add(new campaignmember(campaignid=c.id,contactid=contactList[0].id,status='Attended'));
        cm.add(new campaignmember(campaignid=c.id,contactid=contactList[1].id,status='Attended'));
        insert cm;
        list<Account_Campaign_Junction__c> juctObjList=[select id from Account_Campaign_Junction__c]; 
        system.assertEquals(2, juctObjList.size());
        cm=[select id,contactid,status from campaignmember];
        cm[0].status='Sent';
        //cm[1].status='Sent';
        update cm;
        system.debug(cm[0].status);
        system.debug(cm[1].status);
        juctObjList=[select id from Account_Campaign_Junction__c];
        system.assertEquals(1, juctObjList.size());
    }
}